import { makeStyles, shorthands } from "@fluentui/react-components";

export const useGoalCardPanelStyles = makeStyles({
  root: {
    display: "flex",
    flexDirection: "column",
    ...shorthands.gap("12px"),
    height: "100%",
    overflowY: "auto",
    ...shorthands.padding("16px"),
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    ...shorthands.gap("8px"),
  },
  headerLeft: {
    display: "flex",
    alignItems: "center",
    ...shorthands.gap("8px"),
  },
  statsRow: {
    display: "flex",
    ...shorthands.gap("10px"),
    flexWrap: "wrap",
  },
  statCard: {
    display: "flex",
    flexDirection: "column",
    ...shorthands.gap("2px"),
    ...shorthands.padding("8px", "12px"),
    backgroundColor: "var(--aa-panel)",
    ...shorthands.border("1px", "solid", "var(--aa-border)"),
    ...shorthands.borderRadius("6px"),
    minWidth: "90px",
  },
  statValue: {
    fontFamily: "var(--aa-mono)",
    fontSize: "18px",
    fontWeight: 600,
    color: "var(--aa-text)",
  },
  statLabel: {
    fontSize: "10px",
    fontFamily: "var(--aa-mono)",
    color: "var(--aa-soft)",
    textTransform: "uppercase" as const,
    letterSpacing: "0.04em",
  },
  filterBar: {
    display: "flex",
    ...shorthands.gap("6px"),
    flexWrap: "wrap",
  },
  filterChip: {
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    ...shorthands.gap("4px"),
    ...shorthands.padding("5px", "10px"),
    ...shorthands.borderRadius("6px"),
    fontSize: "11px",
    fontWeight: 600,
    fontFamily: "var(--aa-mono)",
    letterSpacing: "0.02em",
    color: "var(--aa-soft)",
    backgroundColor: "var(--aa-panel)",
    ...shorthands.border("1px", "solid", "var(--aa-border)"),
    transitionProperty: "background-color, border-color, color",
    transitionDuration: "0.15s",
    "&:hover": {
      backgroundColor: "rgba(91, 141, 239, 0.06)",
    },
  },
  filterChipActive: {
    color: "var(--aa-cyan)",
    backgroundColor: "rgba(91, 141, 239, 0.1)",
    ...shorthands.borderColor("var(--aa-cyan)"),
  },
  list: {
    display: "flex",
    flexDirection: "column",
    ...shorthands.gap("6px"),
  },
  card: {
    display: "flex",
    flexDirection: "column",
    ...shorthands.padding("10px", "14px"),
    backgroundColor: "var(--aa-panel)",
    ...shorthands.border("1px", "solid", "var(--aa-border)"),
    ...shorthands.borderRadius("6px"),
    cursor: "pointer",
    transitionProperty: "background-color",
    transitionDuration: "0.15s",
    "&:hover": {
      backgroundColor: "rgba(91, 141, 239, 0.06)",
    },
  },
  cardExpanded: {
    backgroundColor: "rgba(91, 141, 239, 0.08)",
    ...shorthands.borderColor("var(--aa-cyan)"),
  },
  cardHeader: {
    display: "flex",
    alignItems: "center",
    ...shorthands.gap("8px"),
    flexWrap: "wrap",
  },
  agentName: {
    fontSize: "12px",
    fontFamily: "var(--aa-mono)",
    fontWeight: 600,
    color: "var(--aa-text)",
  },
  cardTimestamp: {
    fontSize: "10px",
    fontFamily: "var(--aa-mono)",
    color: "var(--aa-soft)",
    marginLeft: "auto",
    flexShrink: 0,
  },
  cardPreview: {
    fontSize: "12px",
    fontFamily: "var(--aa-mono)",
    color: "var(--aa-muted)",
    ...shorthands.margin("6px", "0", "0"),
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  expandedBody: {
    display: "flex",
    flexDirection: "column",
    ...shorthands.gap("10px"),
    ...shorthands.margin("10px", "0", "0"),
    ...shorthands.padding("10px", "0", "0"),
    ...shorthands.borderTop("1px", "solid", "rgba(255,255,255,0.06)"),
  },
  sectionLabel: {
    fontSize: "10px",
    fontFamily: "var(--aa-mono)",
    fontWeight: 600,
    color: "var(--aa-soft)",
    textTransform: "uppercase" as const,
    letterSpacing: "0.04em",
    ...shorthands.margin("0", "0", "2px"),
  },
  sectionContent: {
    fontSize: "12px",
    fontFamily: "var(--aa-mono)",
    color: "var(--aa-text)",
    lineHeight: "1.5",
    whiteSpace: "pre-wrap",
  },
  freshEyesGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr",
    ...shorthands.gap("8px"),
  },
  freshEyesItem: {
    display: "flex",
    flexDirection: "column",
    ...shorthands.gap("2px"),
    ...shorthands.padding("8px"),
    backgroundColor: "rgba(0, 0, 0, 0.15)",
    ...shorthands.borderRadius("4px"),
    ...shorthands.border("1px", "solid", "rgba(255,255,255,0.04)"),
  },
  taskLink: {
    cursor: "pointer",
    fontSize: "11px",
    fontFamily: "var(--aa-mono)",
    color: "var(--aa-cyan, #5b8def)",
    "&:hover": {
      textDecoration: "underline",
    },
  },
  actionRow: {
    display: "flex",
    alignItems: "center",
    ...shorthands.gap("8px"),
    ...shorthands.padding("6px", "0"),
    ...shorthands.borderTop("1px", "solid", "rgba(255,255,255,0.06)"),
    flexWrap: "wrap",
  },
  actionPrimary: {
    fontFamily: "var(--aa-mono)",
    fontSize: "11px",
    fontWeight: 600,
    color: "var(--aa-cyan, #5b8def)",
    ...shorthands.border("1px", "solid", "var(--aa-cyan, #5b8def)"),
    ...shorthands.borderRadius("4px"),
    "&:hover": {
      backgroundColor: "rgba(91, 141, 239, 0.12)",
    },
  },
  actionDanger: {
    fontFamily: "var(--aa-mono)",
    fontSize: "11px",
    fontWeight: 600,
    color: "var(--aa-err, #f85149)",
    ...shorthands.border("1px", "solid", "var(--aa-err, #f85149)"),
    ...shorthands.borderRadius("4px"),
    "&:hover": {
      backgroundColor: "rgba(248, 81, 73, 0.12)",
    },
  },
  mutateError: {
    fontSize: "11px",
    fontFamily: "var(--aa-mono)",
    color: "var(--aa-err, #f85149)",
  },
});
