import { makeStyles, shorthands } from "@fluentui/react-components";

export const useCommandPaletteStyles = makeStyles({
  backdrop: {
    position: "fixed",
    inset: "0",
    zIndex: 9999,
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "center",
    paddingTop: "min(15vh, 120px)",
    backgroundColor: "rgba(0, 0, 0, 0.55)",
    backdropFilter: "blur(4px)",
  },
  container: {
    width: "min(600px, 90vw)",
    maxHeight: "min(520px, 70vh)",
    display: "flex",
    flexDirection: "column",
    backgroundColor: "var(--aa-panel)",
    border: "1px solid var(--aa-border)",
    boxShadow: "0 24px 80px rgba(0,0,0,0.6), 0 0 1px rgba(91,141,239,0.08)",
    ...shorthands.borderRadius("16px"),
    ...shorthands.overflow("hidden"),
  },
  searchRow: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    ...shorthands.padding("14px", "16px"),
    borderBottom: "1px solid var(--aa-border)",
  },
  searchIcon: {
    color: "var(--aa-soft)",
    fontSize: "18px",
    flexShrink: 0,
  },
  searchInput: {
    flexGrow: 1,
    "& input": {
      backgroundColor: "transparent",
      border: "none",
      color: "#fff",
      fontSize: "15px",
      "&::placeholder": { color: "var(--aa-soft)" },
    },
  },
  hint: {
    flexShrink: 0,
    color: "var(--aa-soft)",
    fontSize: "12px",
  },
  list: {
    overflowY: "auto",
    flexGrow: 1,
    ...shorthands.padding("6px"),
  },
  groupLabel: {
    ...shorthands.padding("8px", "12px", "4px"),
    fontSize: "11px",
    fontWeight: 600,
    textTransform: "uppercase" as const,
    letterSpacing: "0.08em",
    color: "var(--aa-soft)",
  },
  item: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    ...shorthands.padding("8px", "12px"),
    ...shorthands.borderRadius("8px"),
    cursor: "pointer",
    "&:hover": { backgroundColor: "rgba(91, 141, 239, 0.06)" },
  },
  itemSelected: {
    backgroundColor: "rgba(91, 141, 239, 0.08)",
  },
  itemBody: {
    flexGrow: 1,
    display: "flex",
    flexDirection: "column",
    gap: "1px",
    minWidth: 0,
  },
  itemTitle: {
    fontSize: "14px",
    fontWeight: 500,
    color: "#fff",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  itemDesc: {
    fontSize: "12px",
    color: "var(--aa-soft)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  asyncBadge: {
    flexShrink: 0,
  },
  empty: {
    ...shorthands.padding("24px"),
    textAlign: "center",
    color: "var(--aa-soft)",
    fontSize: "13px",
  },
  detailPane: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    ...shorthands.padding("16px"),
    overflowY: "auto",
    flexGrow: 1,
  },
  detailHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "8px",
  },
  detailTitle: {
    fontSize: "16px",
    fontWeight: 600,
    color: "#fff",
  },
  detailDesc: {
    fontSize: "13px",
    color: "var(--aa-muted)",
    lineHeight: "1.4",
  },
  fieldGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  fieldLabel: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: "12px",
    fontWeight: 500,
    color: "var(--aa-muted)",
  },
  fieldHint: {
    fontWeight: 400,
    color: "var(--aa-soft)",
  },
  actionRow: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "8px",
    ...shorthands.padding("8px", "0", "0"),
  },
  resultBox: {
    ...shorthands.padding("12px"),
    ...shorthands.borderRadius("8px"),
    backgroundColor: "rgba(139, 148, 158, 0.04)",
    border: "1px solid var(--aa-border)",
    fontSize: "12px",
    fontFamily: "monospace",
    color: "var(--aa-text)",
    whiteSpace: "pre-wrap",
    maxHeight: "200px",
    overflowY: "auto",
    wordBreak: "break-word",
  },
  resultSuccess: {
    ...shorthands.borderColor("rgba(76, 175, 80, 0.3)"),
  },
  resultError: {
    ...shorthands.borderColor("rgba(232, 93, 93, 0.3)"),
  },
  validationError: {
    color: "var(--aa-copper)",
  },
});
