import { makeStyles, shorthands } from "@fluentui/react-components";

export const useMemoryBrowserStyles = makeStyles({
  root: {
    display: "flex",
    flexDirection: "column",
    ...shorthands.gap("12px"),
    height: "100%",
    overflowY: "auto",
    ...shorthands.padding("16px"),
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    ...shorthands.gap("8px"),
  },
  headerLeft: {
    display: "flex",
    alignItems: "center",
    ...shorthands.gap("8px"),
  },
  controls: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    ...shorthands.gap("8px"),
  },
  searchInput: {
    minWidth: "200px",
    backgroundColor: "var(--aa-panel)",
    color: "var(--aa-text)",
    ...shorthands.border("1px", "solid", "var(--aa-border)"),
    ...shorthands.borderRadius("4px"),
    ...shorthands.padding("4px", "8px"),
    fontSize: "12px",
    fontFamily: "var(--aa-mono)",
    outline: "none",
    "&:focus": {
      ...shorthands.borderColor("var(--aa-cyan)"),
    },
  },
  select: {
    backgroundColor: "var(--aa-panel)",
    color: "var(--aa-text)",
    ...shorthands.border("1px", "solid", "var(--aa-border)"),
    ...shorthands.borderRadius("4px"),
    ...shorthands.padding("4px", "8px"),
    fontSize: "12px",
    fontFamily: "var(--aa-mono)",
    outline: "none",
    cursor: "pointer",
  },
  statsRow: {
    display: "flex",
    ...shorthands.gap("12px"),
    flexWrap: "wrap",
  },
  categoryChips: {
    display: "flex",
    ...shorthands.gap("6px"),
    flexWrap: "wrap",
  },
  categoryChip: {
    display: "inline-flex",
    alignItems: "center",
    ...shorthands.gap("4px"),
    ...shorthands.padding("2px", "8px"),
    ...shorthands.borderRadius("3px"),
    fontSize: "10px",
    fontFamily: "var(--aa-mono)",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    cursor: "pointer",
    backgroundColor: "rgba(139, 148, 158, 0.1)",
    color: "var(--aa-soft)",
    "&:hover": {
      backgroundColor: "rgba(139, 148, 158, 0.2)",
    },
  },
  categoryChipActive: {
    backgroundColor: "rgba(91, 141, 239, 0.15)",
    color: "var(--aa-cyan)",
  },
  list: {
    display: "flex",
    flexDirection: "column",
    ...shorthands.gap("4px"),
  },
  memoryRow: {
    display: "grid",
    gridTemplateColumns: "120px 160px 1fr auto",
    alignItems: "start",
    ...shorthands.gap("8px"),
    ...shorthands.padding("8px", "10px"),
    ...shorthands.borderRadius("4px"),
    backgroundColor: "var(--aa-panel)",
    ...shorthands.border("1px", "solid", "var(--aa-border)"),
    fontSize: "12px",
    fontFamily: "var(--aa-mono)",
    lineHeight: "1.5",
    "&:hover": {
      ...shorthands.borderColor("var(--aa-cyan)"),
    },
  },
  memoryKey: {
    color: "var(--aa-cyan)",
    fontWeight: 600,
    wordBreak: "break-word",
  },
  memoryValue: {
    color: "var(--aa-text)",
    wordBreak: "break-word",
    whiteSpace: "pre-wrap",
  },
  memoryMeta: {
    color: "var(--aa-soft)",
    fontSize: "10px",
  },
  deleteBtn: {
    background: "none",
    ...shorthands.border("none"),
    color: "var(--aa-soft)",
    cursor: "pointer",
    fontSize: "11px",
    ...shorthands.padding("2px", "4px"),
    ...shorthands.borderRadius("3px"),
    "&:hover": {
      color: "var(--aa-copper)",
      backgroundColor: "rgba(232, 93, 93, 0.1)",
    },
  },
  empty: {
    textAlign: "center" as const,
    color: "var(--aa-soft)",
    ...shorthands.padding("32px"),
    fontSize: "13px",
  },
  expandedValue: {
    gridColumn: "1 / -1",
    ...shorthands.padding("8px", "10px"),
    backgroundColor: "rgba(0, 0, 0, 0.2)",
    ...shorthands.borderRadius("3px"),
    color: "var(--aa-text)",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    fontSize: "12px",
    lineHeight: "1.6",
  },
});
