import { makeStyles, shorthands, tokens } from "@fluentui/react-components";

export const useStyles = makeStyles({
  root: {
    minHeight: "100vh",
    color: "var(--aa-text)",
    background: "var(--aa-bg)",
  },
  errorBar: {
    position: "sticky",
    top: tokens.spacingVerticalM,
    zIndex: 2,
    ...shorthands.padding(tokens.spacingVerticalM, tokens.spacingHorizontalL, "0"),
  },
  shell: {
    display: "flex",
    height: "100vh",
    width: "100vw",
    overflow: "hidden",
  },
  shellOpen: {
    /* sidebar visible — default */
  },
  shellCollapsed: {
    /* sidebar collapsed — narrower sidebar handled by sidebar class */
  },

  /* ═══ SIDEBAR ═══ */
  sidebar: {
    width: "var(--sidebar-width)",
    minWidth: "var(--sidebar-width)",
    height: "100%",
    background: "var(--aa-panel)",
    borderRight: "1px solid var(--aa-border)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  sidebarCollapsed: {
    width: "48px",
    minWidth: "48px",
  },
  sidebarHeader: {
    borderBottom: "1px solid var(--aa-border)",
    ...shorthands.padding("10px", "14px", "12px"),
  },
  sidebarToolbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: tokens.spacingHorizontalS,
  },
  brandBlock: {
    display: "grid",
    gap: "2px",
  },
  appTitle: {
    fontFamily: "var(--sans)",
    fontSize: "14px",
    fontWeight: 700,
    letterSpacing: "-0.02em",
    color: "var(--aa-text-strong)",
    lineHeight: 1.2,
  },
  appSubtitle: {
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    fontFamily: "var(--mono)",
    fontSize: "10px",
    color: "var(--aa-lime)",
  },
  eyebrow: {
    display: "inline-flex",
    alignItems: "center",
    width: "fit-content",
    gap: "4px",
    color: "var(--aa-lime)",
    fontSize: "10px",
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  sidebarBody: { flex: 1, overflowY: "auto", paddingBottom: "8px" },
  section: {
    ...shorthands.padding("4px", "8px"),
  },
  sectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: tokens.spacingHorizontalS,
    ...shorthands.padding("10px", "10px", "3px"),
  },
  sectionCount: {
    fontFamily: "var(--mono)",
    fontSize: "9px",
    fontWeight: 500,
    color: "var(--aa-cyan)",
    backgroundColor: "rgba(91, 141, 239, 0.12)",
    ...shorthands.borderRadius("3px"),
    ...shorthands.padding("1px", "5px"),
  },
  sectionLabel: {
    color: "var(--aa-soft)",
    fontSize: "10px",
    fontWeight: 600,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  roomList: { display: "grid", gap: "1px" },
  sidebarUtilityRow: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
  },
  sidebarIconButton: {
    minWidth: "24px",
    width: "24px",
    height: "24px",
    color: "var(--aa-soft)",
    backgroundColor: "transparent",
    border: "none",
    ":hover": {
      backgroundColor: "rgba(91, 141, 239, 0.06)",
      color: "var(--aa-text)",
    },
  },
  sidebarProjectCard: {
    ...shorthands.padding("6px", "0", "0"),
  },
  sidebarProjectLabel: {
    color: "var(--aa-soft)",
    fontSize: "10px",
    fontWeight: 600,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  sidebarProjectRow: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  sidebarProjectIcon: {
    width: "20px",
    height: "20px",
    display: "grid",
    placeItems: "center",
    fontSize: "12px",
  },
  sidebarProjectName: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "var(--aa-text)",
    fontSize: "11px",
    fontWeight: 500,
    flex: 1,
    minWidth: 0,
  },
  sidebarProjectPath: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "var(--aa-soft)",
    fontSize: "10px",
  },
  sidebarProjectAction: {
    minWidth: "auto",
    height: "24px",
    color: "var(--aa-soft)",
  },
  sidebarSnapshotGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: "6px",
  },
  sidebarSnapshotCard: {
    display: "grid",
    gap: "2px",
    ...shorthands.padding("4px"),
  },
  sidebarSnapshotValue: {
    color: "var(--aa-text-strong)",
    fontSize: "14px",
    fontWeight: 700,
  },
  sidebarSnapshotLabel: {
    color: "var(--aa-soft)",
    fontSize: "9px",
    fontWeight: 600,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },

  /* ─ Nav Items (view switching in sidebar) ─ */
  navSection: {
    ...shorthands.padding("4px", "8px"),
  },
  navItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    width: "100%",
    ...shorthands.padding("6px", "10px"),
    ...shorthands.borderRadius("6px"),
    color: "var(--aa-soft)",
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: "14px",
    border: "none",
    background: "transparent",
    textAlign: "left",
    borderLeft: "2px solid transparent",
    cursor: "pointer",
    transitionProperty: "all",
    transitionDuration: "0.12s",
    ":hover": {
      color: "var(--aa-muted)",
      background: "rgba(91, 141, 239, 0.06)",
    },
  },
  navItemActive: {
    color: "var(--aa-cyan)",
    background: "rgba(91, 141, 239, 0.12)",
    borderLeftColor: "var(--aa-cyan)",
  },
  navIcon: {
    width: "16px",
    textAlign: "center",
    fontSize: "13px",
    flexShrink: 0,
  },

  /* ─ Sidebar Room Items ─ */
  roomButton: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: "7px",
    border: "none",
    background: "transparent",
    color: "var(--aa-muted)",
    cursor: "pointer",
    textAlign: "left",
    ...shorthands.borderRadius("5px"),
    ...shorthands.padding("4px", "10px"),
    fontSize: "11px",
    lineHeight: "14px",
    transitionProperty: "all",
    transitionDuration: "0.12s",
  },
  roomButtonHover: {
    ":hover": {
      background: "rgba(91, 141, 239, 0.06)",
      color: "var(--aa-text)",
    },
  },
  roomButtonActive: {
    background: "rgba(91, 141, 239, 0.12)",
    color: "var(--aa-text-strong)",
  },
  roomButtonIcon: {
    display: "none",
  },
  roomButtonName: {
    fontSize: "11px",
    fontWeight: 500,
    color: "inherit",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    flex: 1,
    minWidth: 0,
  },
  roomButtonBody: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    minWidth: 0,
    flex: 1,
  },
  roomButtonTopRow: {
    display: "none",
  },
  roomButtonMeta: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
  },
  roomPhaseLabel: {
    display: "none",
  },
  roomButtonCount: {
    marginLeft: "auto",
    fontFamily: "var(--mono)",
    fontSize: "9px",
    fontWeight: 500,
    color: "var(--aa-cyan)",
    backgroundColor: "rgba(91, 141, 239, 0.12)",
    ...shorthands.borderRadius("3px"),
    ...shorthands.padding("1px", "5px"),
    letterSpacing: "0.03em",
    textTransform: "uppercase",
    flexShrink: 0,
  },
  roomButtonTitleWrap: {
    minWidth: 0,
    flex: 1,
  },
  roomButtonTask: {
    display: "none",
  },
  roomPhaseDot: {
    width: "6px",
    height: "6px",
    ...shorthands.borderRadius("50%"),
    flexShrink: 0,
  },
  compactSidebar: {
    flex: 1,
    display: "grid",
    alignContent: "start",
    gap: "8px",
    ...shorthands.padding("8px", "4px"),
  },
  compactSidebarMarker: {
    width: "100%",
    height: "32px",
    display: "grid",
    placeItems: "center",
    color: "var(--aa-text)",
    fontSize: "10px",
    fontWeight: 700,
  },
  compactButton: {
    position: "relative" as const,
    width: "100%",
    height: "36px",
    border: "none",
    background: "transparent",
    color: "var(--aa-muted)",
    cursor: "pointer",
    fontWeight: 600,
    fontSize: "10px",
    ...shorthands.borderRadius("6px"),
    ":hover": {
      background: "rgba(91, 141, 239, 0.06)",
      color: "var(--aa-text)",
    },
  },
  compactButtonActive: {
    background: "rgba(91, 141, 239, 0.12)",
    color: "var(--aa-text-strong)",
  },
  compactRoomDot: {
    position: "absolute" as const,
    top: "4px",
    right: "4px",
    width: "5px",
    height: "5px",
    ...shorthands.borderRadius("50%"),
  },
  sidebarRoomHeader: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    ...shorthands.padding("8px", "10px"),
    borderBottom: "1px solid var(--aa-border)",
    fontSize: "12px",
    fontWeight: 600,
    color: "var(--aa-text)",
  },
  sidebarRoomDot: {
    width: "6px",
    height: "6px",
    ...shorthands.borderRadius("999px"),
    flexShrink: 0,
  },
  agentListItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    ...shorthands.padding("4px", "10px"),
    fontSize: "11px",
    color: "var(--aa-muted)",
  },
  agentStateDot: {
    width: "6px",
    height: "6px",
    ...shorthands.borderRadius("999px"),
    flexShrink: 0,
  },
  roomAgentList: {
    gridColumn: "1 / -1",
    display: "none",
  },
  roomAgentItem: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "11px",
    color: "var(--aa-soft)",
  },

  /* ─ Agent Workspace Items in Sidebar ─ */
  workspaceButton: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: "7px",
    border: "none",
    background: "transparent",
    color: "var(--aa-muted)",
    cursor: "pointer",
    textAlign: "left",
    ...shorthands.borderRadius("5px"),
    ...shorthands.padding("4px", "10px"),
    fontSize: "11px",
    lineHeight: "14px",
    transitionProperty: "all",
    transitionDuration: "0.12s",
  },
  workspaceButtonBody: {
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    gap: "6px",
    flex: 1,
  },
  workspaceButtonTopRow: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    minWidth: 0,
    flex: 1,
  },
  workspaceIcon: {
    display: "none",
  },
  workspaceName: {
    fontSize: "11px",
    fontWeight: 500,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  workspaceRole: {
    display: "none",
  },
  workspaceStateBadge: {
    fontSize: "9px",
    fontWeight: 500,
    letterSpacing: "0.03em",
    ...shorthands.borderRadius("3px"),
    ...shorthands.padding("1px", "5px"),
    marginLeft: "auto",
    textTransform: "uppercase",
  },
  workspaceTask: {
    display: "none",
  },

  /* ─ User Area (bottom of sidebar) ─ */
  userArea: {
    borderTop: "1px solid var(--aa-border)",
    ...shorthands.padding("8px", "14px"),
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "11px",
    color: "var(--aa-soft)",
  },
  userAvatar: {
    width: "22px",
    height: "22px",
    ...shorthands.borderRadius("50%"),
    background: "linear-gradient(135deg, var(--aa-cyan), var(--special))",
    display: "grid",
    placeItems: "center",
    fontSize: "9px",
    fontWeight: 700,
    color: "white",
    flexShrink: 0,
  },

  /* ═══ MAIN AREA ═══ */
  workspace: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    minWidth: 0,
  },

  /* ─ Header (40px page title row) ─ */
  headerDivider: {
    width: "1px",
    height: "16px",
    background: "var(--aa-border)",
    flexShrink: 0,
  },
  workspaceHeader: {
    height: "var(--topbar-height)",
    minHeight: "var(--topbar-height)",
    background: "var(--aa-panel)",
    borderBottom: "1px solid var(--aa-border)",
    display: "flex",
    alignItems: "center",
    ...shorthands.padding("0", "16px"),
    gap: "10px",
  },
  workspaceHeaderBody: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    minWidth: 0,
    flex: 1,
  },
  workspaceHeaderTopRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "10px",
    flex: 1,
    minWidth: 0,
  },
  workspaceHeaderSignals: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flexShrink: 0,
  },
  workspaceSignal: {
    display: "inline-flex",
    alignItems: "center",
    fontFamily: "var(--mono)",
    fontSize: "9px",
    fontWeight: 600,
    ...shorthands.borderRadius("4px"),
    ...shorthands.padding("2px", "7px"),
    backgroundColor: "rgba(91, 141, 239, 0.12)",
    color: "var(--aa-cyan)",
  },
  workspaceSignalWarning: {
    backgroundColor: "rgba(255, 152, 0, 0.12)",
    color: "var(--aa-gold)",
  },
  workspaceTitle: {
    fontSize: "14px",
    fontWeight: 600,
    color: "var(--aa-text-strong)",
    letterSpacing: "-0.01em",
    whiteSpace: "nowrap" as const,
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  workspaceSubtitle: {
    display: "none",
  },
  workspaceMetaRow: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    color: "var(--aa-soft)",
    fontFamily: "var(--mono)",
    fontSize: "10px",
  },
  workspaceMetaChip: {
    display: "none",
  },
  workspaceMetaSep: {
    color: "var(--aa-border)",
    userSelect: "none" as const,
  },
  workspaceMetaText: {
    color: "var(--aa-soft)",
    fontFamily: "var(--mono)",
    fontSize: "10px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  phasePill: {
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    fontFamily: "var(--mono)",
    fontSize: "9px",
    fontWeight: 600,
    color: "var(--aa-lime)",
    backgroundColor: "rgba(76, 175, 80, 0.12)",
    ...shorthands.borderRadius("4px"),
    ...shorthands.padding("2px", "7px"),
  },
  phasePillDot: {
    width: "5px",
    height: "5px",
    backgroundColor: "var(--aa-lime)",
    ...shorthands.borderRadius("50%"),
    animation: "aa-pulse 2s ease-in-out infinite",
  },
  limitedModeBanner: {
    display: "grid",
    gap: "8px",
    borderBottom: "1px solid var(--aa-border)",
    background: "rgba(255, 152, 0, 0.06)",
    ...shorthands.padding("12px", "16px"),
  },
  limitedModeBadge: {
    display: "inline-flex",
    alignItems: "center",
    width: "fit-content",
    fontFamily: "var(--mono)",
    fontSize: "10px",
    fontWeight: 600,
    color: "var(--aa-gold)",
    backgroundColor: "rgba(255, 152, 0, 0.12)",
    border: "1px solid rgba(255, 152, 0, 0.2)",
    ...shorthands.borderRadius("4px"),
    ...shorthands.padding("2px", "8px"),
    textTransform: "uppercase",
  },
  limitedModeTitle: {
    color: "var(--aa-text-strong)",
    fontSize: "13px",
    fontWeight: 600,
  },
  limitedModeDescription: {
    color: "var(--aa-muted)",
    fontSize: "12px",
    lineHeight: 1.5,
  },

  /* ─ Contextual Toolbar (34px, below header) ─ */
  tabBar: {
    height: "var(--toolbar-height)",
    minHeight: "var(--toolbar-height)",
    background: "var(--aa-bg)",
    borderBottom: "1px solid var(--aa-border)",
    display: "flex",
    alignItems: "center",
    ...shorthands.padding("0", "16px"),
    gap: "8px",
    fontSize: "11px",
  },
  tabList: {
    display: "flex",
    gap: "6px",
    alignItems: "center",
    "& [role=tab]": {
      display: "inline-flex",
      alignItems: "center",
      gap: "5px",
      minHeight: "26px",
      color: "var(--aa-muted)",
      backgroundColor: "transparent",
      border: "1px solid var(--aa-border)",
      ...shorthands.borderRadius("4px"),
      ...shorthands.padding("3px", "9px"),
      fontSize: "11px",
      fontWeight: 500,
      transitionProperty: "all",
      transitionDuration: "0.12s",
    },
    "& [role=tab]:hover": {
      ...shorthands.borderColor("var(--aa-border-strong)"),
      color: "var(--aa-text)",
      background: "rgba(91, 141, 239, 0.04)",
    },
    "& [role=tab][aria-selected=true]": {
      background: "rgba(91, 141, 239, 0.12)",
      color: "var(--aa-cyan)",
      ...shorthands.borderColor("rgba(91, 141, 239, 0.3)"),
    },
  },
  tabStrip: {
    display: "flex",
    gap: "6px",
    alignItems: "center",
    flex: 1,
    minWidth: 0,
  },
  tabLabelStack: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    minWidth: 0,
  },
  tabLabelTitle: {
    fontSize: "11px",
    fontWeight: 500,
    lineHeight: 1.2,
  },
  tabLabelDetail: {
    display: "none",
  },
  overflowTrigger: {
    display: "inline-flex",
    gap: "5px",
    alignItems: "center",
    minHeight: "26px",
    color: "var(--aa-soft)",
    backgroundColor: "transparent",
    border: "1px solid var(--aa-border)",
    ...shorthands.borderRadius("4px"),
    ...shorthands.padding("3px", "9px"),
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: "11px",
    fontWeight: 500,
    "&:hover": {
      ...shorthands.borderColor("var(--aa-border-strong)"),
      color: "var(--aa-text)",
      background: "rgba(91, 141, 239, 0.04)",
    },
  },
  overflowTriggerActive: {
    background: "rgba(91, 141, 239, 0.12)",
    color: "var(--aa-cyan)",
    ...shorthands.borderColor("rgba(91, 141, 239, 0.3)"),
  },
  overflowItemActive: {
    fontWeight: 700,
  },

  /* ─ Content ─ */
  tabContent: {
    flex: 1,
    minHeight: 0,
    display: "grid",
    gridTemplateRows: "minmax(0, 1fr)",
    overflow: "auto",
    ...shorthands.padding("0"),
  },

  /* ═══ CONVERSATION / CHAT ═══ */
  conversationLayout: {
    minHeight: 0,
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr) auto auto",
    gap: "0",
  },
  messageList: {
    minHeight: 0,
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    ...shorthands.padding("14px", "20px"),
  },
  systemMessage: {
    fontFamily: "var(--mono)",
    fontSize: "11px",
    color: "var(--aa-soft)",
    fontStyle: "italic",
    ...shorthands.padding("5px", "12px"),
    ...shorthands.borderRadius("6px"),
    background: "var(--aa-panel-alt)",
    textAlign: "center",
    maxWidth: "80%",
    alignSelf: "center",
  },
  bubble: {
    display: "flex",
    flexDirection: "column",
    gap: "0",
    background: "var(--aa-panel)",
    border: "1px solid var(--aa-border)",
    ...shorthands.borderRadius("8px"),
    ...shorthands.padding("12px", "14px"),
  },
  bubbleCard: {
    flex: 1,
    minWidth: 0,
    background: "transparent",
    border: "none",
    boxShadow: "none",
    ...shorthands.padding("0"),
    ...shorthands.borderRadius("0"),
  },
  bubbleHeader: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginBottom: "6px",
  },
  rolePill: {
    display: "inline-flex",
    alignItems: "center",
    fontFamily: "var(--mono)",
    ...shorthands.borderRadius("3px"),
    ...shorthands.padding("3px", "6px", "2px"),
    fontSize: "9px",
    lineHeight: "1",
    fontWeight: 600,
    textTransform: "uppercase",
  },
  messageTime: {
    marginLeft: "auto",
    color: "var(--aa-soft)",
    fontFamily: "var(--mono)",
    fontSize: "10px",
  },
  bubbleText: {
    whiteSpace: "pre-wrap",
    lineHeight: 1.6,
    color: "var(--aa-text)",
    fontFamily: "var(--mono)",
    fontSize: "13px",
    wordBreak: "break-word",
  },
  bubbleCollapsed: {
    maxHeight: "160px",
    overflow: "hidden",
    maskImage: "linear-gradient(to bottom, black 65%, transparent 100%)",
    WebkitMaskImage: "linear-gradient(to bottom, black 65%, transparent 100%)",
  },
  expandButton: {
    marginTop: "4px",
    border: "none",
    background: "none",
    color: "var(--aa-cyan)",
    cursor: "pointer",
    padding: 0,
    fontSize: "11px",
    fontWeight: 600,
  },
  thinkingCard: {
    borderLeftWidth: "2px",
    borderLeftStyle: "solid",
    borderLeftColor: "var(--aa-cyan)",
    opacity: 0.95,
  },
  thinkingDots: { display: "inline-flex", gap: "3px", color: "var(--aa-soft)", fontSize: "12px" },

  /* ── Command Result Styles ────────────────────────────────── */
  commandResultBlock: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "2px",
    background: "rgba(0, 150, 136, 0.08)",
    borderLeft: "3px solid var(--tool)",
    ...shorthands.borderRadius("0", "6px", "6px", "0"),
    ...shorthands.padding("6px", "12px"),
    fontSize: "11px",
    fontFamily: "var(--mono)",
  },
  commandResultItem: {
    cursor: "pointer",
    ...shorthands.borderRadius("4px"),
    "&[open]": {
      backgroundColor: "rgba(255, 255, 255, 0.02)",
    },
  },
  commandResultSummary: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    listStyle: "none",
    ...shorthands.padding("2px", "6px"),
    ...shorthands.borderRadius("4px"),
    "&::-webkit-details-marker": { display: "none" },
    "&:hover": { backgroundColor: "rgba(255, 255, 255, 0.03)" },
  },
  commandStatusOk: { fontSize: "12px" },
  commandStatusErr: { fontSize: "12px" },
  commandName: {
    fontFamily: "var(--mono)",
    fontWeight: 600,
    color: "var(--tool)",
    fontSize: "11px",
  },
  commandError: {
    color: "var(--error)",
    fontSize: "10px",
    marginLeft: "auto",
    fontStyle: "italic",
  },
  commandDetail: {
    margin: 0,
    ...shorthands.padding("4px", "10px"),
    fontSize: "10px",
    color: "var(--aa-soft)",
    backgroundColor: "rgba(0, 0, 0, 0.2)",
    ...shorthands.borderRadius("4px"),
    overflowX: "auto" as const,
    maxHeight: "100px",
    whiteSpace: "pre-wrap" as const,
    wordBreak: "break-word" as const,
  },

  /* ── Filter Menu ────────────────────────────────────────── */
  chatHeader: {
    display: "flex",
    justifyContent: "flex-end",
    ...shorthands.padding("4px", "8px"),
    flexShrink: 0,
  },
  filterMenuButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    fontSize: "11px",
    color: "var(--aa-soft)",
  },
  filterBadge: {
    minWidth: "14px",
    height: "14px",
    fontSize: "9px",
  },
  statusBar: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    color: "var(--aa-soft)",
    backgroundColor: "rgba(91, 141, 239, 0.04)",
    border: "1px solid var(--aa-border)",
    ...shorthands.borderRadius("4px"),
    ...shorthands.padding("4px", "10px"),
    fontSize: "11px",
    fontFamily: "var(--mono)",
  },
  statusIndicator: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "14px",
    height: "14px",
    ...shorthands.borderRadius("999px"),
    fontSize: "10px",
    flexShrink: 0,
  },
  composerShell: {
    borderTop: "1px solid var(--aa-border)",
    background: "var(--aa-panel)",
    ...shorthands.borderRadius("0"),
    ...shorthands.padding("10px", "16px"),
  },
  composerLabel: {
    marginBottom: "4px",
    color: "var(--aa-soft)",
    fontFamily: "var(--mono)",
    fontSize: "10px",
  },
  composerField: { width: "100%" },
  composerActions: {
    marginTop: "8px",
    display: "flex",
    justifyContent: "flex-end",
    gap: "8px",
  },
  emptyState: { color: "var(--aa-soft)" },

  /* ═══ TASK CARD (shared) ═══ */
  taskCard: {
    border: "1px solid var(--aa-border)",
    backgroundColor: "var(--aa-panel)",
    ...shorthands.borderRadius("8px"),
    ...shorthands.padding("14px"),
  },
  taskCardTitle: { marginBottom: "8px", fontSize: "13px", fontWeight: 600 },
  form: { display: "grid", gap: "10px" },
  fieldInput: { width: "100%" },

  /* ═══ RECOVERY BANNERS ═══ */
  recoveryBannerGlobal: {
    position: "fixed",
    top: "8px",
    left: "50%",
    transform: "translateX(-50%)",
    zIndex: 1000,
    maxWidth: "480px",
    width: "calc(100% - 32px)",
  },
  recoveryBanner: {
    justifySelf: "stretch",
    display: "grid",
    gap: "8px",
    border: "1px solid var(--aa-border)",
    boxShadow: "var(--aa-shadow)",
    ...shorthands.borderRadius("8px"),
    ...shorthands.padding("12px", "14px"),
  },
  recoveryBannerSyncing: {
    background: "var(--aa-panel)",
    ...shorthands.borderColor("rgba(91, 141, 239, 0.3)"),
  },
  recoveryBannerReconnecting: {
    background: "var(--aa-panel)",
    ...shorthands.borderColor("rgba(255, 152, 0, 0.3)"),
  },
  recoveryBannerCrash: {
    background: "var(--aa-panel)",
    ...shorthands.borderColor("rgba(232, 93, 93, 0.3)"),
  },
  recoveryBannerError: {
    background: "var(--aa-panel)",
    ...shorthands.borderColor("rgba(232, 93, 93, 0.3)"),
  },
  recoveryBannerBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    width: "fit-content",
    fontFamily: "var(--mono)",
    fontSize: "10px",
    fontWeight: 600,
    color: "var(--aa-text-strong)",
    ...shorthands.borderRadius("4px"),
    ...shorthands.padding("2px", "8px"),
    textTransform: "uppercase",
  },
  recoveryBannerAlert: {
    width: "14px",
    height: "14px",
    display: "inline-grid",
    placeItems: "center",
    ...shorthands.borderRadius("999px"),
    fontSize: "10px",
    fontWeight: 700,
  },
  recoveryBannerBody: {
    display: "grid",
    gap: "4px",
  },
  recoveryBannerMessage: {
    color: "var(--aa-text-strong)",
    fontSize: "13px",
    fontWeight: 600,
  },
  recoveryBannerDetail: {
    color: "var(--aa-soft)",
    fontSize: "12px",
    lineHeight: 1.4,
  },
});
