import { makeStyles, shorthands, tokens } from "@fluentui/react-components";

export const useStyles = makeStyles({
  root: {
    minHeight: "100vh",
    color: "var(--aa-text)",
    background:
      "radial-gradient(circle at top left, rgba(108, 182, 255, 0.08), transparent 26%), radial-gradient(circle at top right, rgba(167, 139, 250, 0.08), transparent 22%), radial-gradient(circle at bottom, rgba(217, 166, 103, 0.06), transparent 30%), linear-gradient(180deg, rgba(4, 8, 15, 0.98), rgba(8, 14, 24, 1))",
  },
  errorBar: {
    position: "sticky",
    top: tokens.spacingVerticalM,
    zIndex: 2,
    ...shorthands.padding(tokens.spacingVerticalM, tokens.spacingHorizontalL, "0"),
  },
  shell: {
    display: "grid",
    gap: "20px",
    height: "100vh",
    boxSizing: "border-box",
    gridTemplateRows: "minmax(0, 1fr)",
    ...shorthands.padding("18px"),
    "@media (max-width: 900px)": {
      gap: "16px",
      ...shorthands.padding("14px"),
    },
  },
  shellOpen: {
    gridTemplateColumns: "320px minmax(0, 1fr)",
    "@media (max-width: 1100px)": {
      gridTemplateColumns: "280px minmax(0, 1fr)",
    },
    "@media (max-width: 900px)": {
      gridTemplateColumns: "1fr",
      gridTemplateRows: "minmax(220px, auto) minmax(0, 1fr)",
    },
  },
  shellCollapsed: { gridTemplateColumns: "88px minmax(0, 1fr)" },
  sidebar: {
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    borderRadius: "32px",
    border: "1px solid rgba(163, 180, 208, 0.16)",
    background: "linear-gradient(180deg, rgba(13, 22, 37, 0.9), rgba(8, 14, 24, 0.97))",
    boxShadow: "var(--aa-shadow)",
    overflow: "hidden",
  },
  sidebarCollapsed: { alignItems: "center" },
  sidebarHeader: {
    display: "grid",
    gap: "12px",
    borderBottom: "1px solid rgba(163, 180, 208, 0.16)",
    ...shorthands.padding("26px", "24px", "22px"),
  },
  sidebarToolbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: tokens.spacingHorizontalS,
  },
  appTitle: { fontFamily: "var(--heading)", fontSize: "26px", fontWeight: 700, letterSpacing: "-0.05em", color: "#f7fbff" },
  eyebrow: {
    display: "inline-flex",
    alignItems: "center",
    width: "fit-content",
    gap: "8px",
    color: "#f3d4a8",
    backgroundColor: "rgba(217, 166, 103, 0.12)",
    border: "1px solid rgba(217, 166, 103, 0.22)",
    ...shorthands.borderRadius("999px"),
    ...shorthands.padding("7px", "13px"),
    fontSize: "11px",
    fontWeight: 700,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
  },
  sidebarBody: { flex: 1, overflowY: "auto" },
  section: {
    display: "grid",
    gap: "12px",
    borderTop: "1px solid rgba(155, 176, 210, 0.16)",
    ...shorthands.padding("18px", "18px", "20px"),
  },
  sectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: tokens.spacingHorizontalS,
  },
  sectionLabel: {
    color: "#7f94b6",
    fontSize: "11px",
    fontWeight: 700,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
  },
  roomList: { display: "grid", gap: "8px" },
  sidebarUtilityRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  sidebarIconButton: {
    minWidth: "32px",
    width: "32px",
    height: "32px",
    color: "#9bb0d2",
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    border: "1px solid rgba(255, 255, 255, 0.05)",
    ":hover": {
      backgroundColor: "rgba(255, 255, 255, 0.06)",
      color: "#eff5ff",
    },
  },
  sidebarProjectCard: {
    display: "grid",
    gap: "10px",
    border: "1px solid rgba(163, 180, 208, 0.12)",
    background: "linear-gradient(180deg, rgba(255, 255, 255, 0.035), rgba(255, 255, 255, 0.015))",
    ...shorthands.borderRadius("20px"),
    ...shorthands.padding("12px", "14px"),
  },
  sidebarProjectLabel: {
    color: "#7f94b6",
    fontSize: "10px",
    fontWeight: 700,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
  },
  sidebarProjectRow: {
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr) auto",
    alignItems: "center",
    gap: "10px",
  },
  sidebarProjectIcon: {
    width: "30px",
    height: "30px",
    display: "grid",
    placeItems: "center",
    color: "#f3d4a8",
    backgroundColor: "rgba(217, 166, 103, 0.12)",
    border: "1px solid rgba(217, 166, 103, 0.18)",
    ...shorthands.borderRadius("12px"),
    fontSize: "14px",
  },
  sidebarProjectName: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "#eef4ff",
    fontSize: "13px",
    fontWeight: 650,
  },
  sidebarProjectPath: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "#7f94b6",
    fontSize: "11px",
  },
  sidebarProjectAction: {
    minWidth: "auto",
    height: "28px",
    color: "#9bb0d2",
  },
  roomButton: {
    width: "100%",
    display: "grid",
    gridTemplateColumns: "40px 1fr",
    gap: "14px",
    alignItems: "center",
    border: "1px solid transparent",
    background: "transparent",
    color: "inherit",
    cursor: "pointer",
    textAlign: "left",
    ...shorthands.borderRadius("18px"),
    ...shorthands.padding("14px"),
  },
  roomButtonHover: {
    ":hover": {
      backgroundColor: "rgba(255, 255, 255, 0.035)",
      border: "1px solid rgba(255, 255, 255, 0.08)",
    },
  },
  roomButtonActive: {
    background: "linear-gradient(135deg, rgba(131, 207, 255, 0.16), rgba(217, 166, 103, 0.08))",
    border: "1px solid rgba(131, 207, 255, 0.28)",
    boxShadow: "inset 0 1px 0 rgba(255, 255, 255, 0.05)",
  },
  roomButtonIcon: {
    width: "40px",
    height: "40px",
    display: "grid",
    placeItems: "center",
    color: "#0b1320",
    fontSize: "14px",
    fontWeight: 800,
    background: "linear-gradient(145deg, #f3d4a8, #83cfff)",
    boxShadow: "0 10px 26px rgba(0, 0, 0, 0.25)",
    ...shorthands.borderRadius("14px"),
  },
  roomButtonName: { fontSize: "14px", fontWeight: 650 },
  roomButtonMeta: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  roomPhaseDot: {
    width: "6px",
    height: "6px",
    ...shorthands.borderRadius("999px"),
    flexShrink: 0,
  },
  compactSidebar: {
    flex: 1,
    display: "grid",
    alignContent: "start",
    gap: "12px",
    ...shorthands.padding("18px", "12px"),
  },
  compactButton: {
    width: "100%",
    height: "52px",
    border: "1px solid transparent",
    background: "rgba(255, 255, 255, 0.03)",
    color: "#eff5ff",
    cursor: "pointer",
    fontWeight: 760,
    ...shorthands.borderRadius("18px"),
  },
  compactButtonActive: {
    border: "1px solid rgba(108, 182, 255, 0.34)",
    background: "linear-gradient(180deg, rgba(108, 182, 255, 0.14), rgba(65, 135, 255, 0.08))",
  },
  sidebarRoomHeader: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    ...shorthands.padding("12px", "18px"),
    borderBottom: "1px solid rgba(155, 176, 210, 0.16)",
    fontSize: "13px",
    fontWeight: 650,
    color: "#eff5ff",
  },
  sidebarRoomDot: {
    width: "8px",
    height: "8px",
    ...shorthands.borderRadius("999px"),
    flexShrink: 0,
  },
  agentListItem: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    ...shorthands.padding("8px", "24px"),
    fontSize: "13px",
    color: "#dbe7fb",
  },
  agentStateDot: {
    width: "8px",
    height: "8px",
    ...shorthands.borderRadius("999px"),
    flexShrink: 0,
  },
  roomAgentList: {
    gridColumn: "1 / -1",
    marginTop: "6px",
    paddingTop: "6px",
    borderTop: "1px solid rgba(155, 176, 210, 0.12)",
    display: "flex",
    flexDirection: "column" as const,
    gap: "4px",
  },
  roomAgentItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "12px",
    color: "#a1b3d2",
  },
  workspaceButton: {
    width: "100%",
    display: "grid",
    gridTemplateColumns: "32px 1fr",
    gap: "10px",
    alignItems: "center",
    border: "1px solid transparent",
    background: "transparent",
    color: "inherit",
    cursor: "pointer",
    textAlign: "left",
    ...shorthands.borderRadius("14px"),
    ...shorthands.padding("10px", "12px"),
  },
  workspaceIcon: {
    width: "32px",
    height: "32px",
    display: "grid",
    placeItems: "center",
    color: "#ffffff",
    fontSize: "13px",
    fontWeight: 760,
    boxShadow: "0 4px 12px rgba(79, 140, 255, 0.15)",
    ...shorthands.borderRadius("10px"),
  },
  workspaceName: {
    fontSize: "13px",
    fontWeight: 620,
  },
  workspaceStateBadge: {
    fontSize: "9px",
    fontWeight: 700,
    letterSpacing: "0.04em",
    ...shorthands.borderRadius("999px"),
    ...shorthands.padding("2px", "6px"),
  },
  workspaceTask: {
    fontSize: "11px",
    color: "#7c90b2",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  taskCard: {
    border: "1px solid rgba(255, 255, 255, 0.06)",
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    contain: "layout paint",
    ...shorthands.borderRadius("22px"),
    ...shorthands.padding("16px"),
  },
  taskCardTitle: { marginBottom: "12px", fontSize: "14px", fontWeight: 680 },
  form: { display: "grid", gap: "12px" },
  fieldInput: { width: "100%" },
  workspace: {
    minHeight: 0,
    display: "grid",
    gridTemplateRows: "auto auto minmax(0, 1fr)",
    borderRadius: "32px",
    border: "1px solid rgba(163, 180, 208, 0.16)",
    background: "linear-gradient(180deg, rgba(18, 30, 48, 0.92), rgba(9, 15, 25, 0.98))",
    boxShadow: "var(--aa-shadow)",
    overflow: "hidden",
    backdropFilter: "blur(14px)",
  },
  workspaceHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "18px",
    borderBottom: "1px solid rgba(163, 180, 208, 0.16)",
    background: "linear-gradient(180deg, rgba(255, 255, 255, 0.035), transparent)",
    ...shorthands.padding("28px", "30px", "22px"),
    "@media (max-width: 900px)": {
      ...shorthands.padding("22px", "22px", "18px"),
    },
  },
  workspaceTitle: { fontFamily: "var(--heading)", fontSize: "38px", fontWeight: 700, letterSpacing: "-0.05em", color: "#f8fbff" },
  workspaceSubtitle: {
    marginTop: "10px",
    maxWidth: "760px",
    color: "#aec0de",
    fontSize: "14px",
    lineHeight: 1.75,
  },
  phasePill: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    color: "#f8e2bf",
    backgroundColor: "rgba(217, 166, 103, 0.1)",
    border: "1px solid rgba(217, 166, 103, 0.2)",
    ...shorthands.borderRadius("999px"),
    ...shorthands.padding("10px", "14px"),
    fontSize: "12px",
    fontWeight: 700,
  },
  tabBar: {
    borderBottom: "1px solid rgba(163, 180, 208, 0.12)",
    background: "linear-gradient(180deg, rgba(255, 255, 255, 0.025), rgba(255, 255, 255, 0))",
    ...shorthands.padding("14px", "24px", "0"),
  },
  tabContent: {
    minHeight: 0,
    display: "grid",
    gridTemplateRows: "minmax(0, 1fr)",
    ...shorthands.padding("22px", "24px", "24px"),
    "@media (max-width: 900px)": {
      ...shorthands.padding("18px", "18px", "20px"),
    },
  },
  conversationLayout: {
    minHeight: 0,
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr) auto auto",
    gap: "0",
  },
  messageList: {
    minHeight: 0,
    overflowY: "auto",
    display: "grid",
    alignContent: "start",
    gap: "16px",
    ...shorthands.padding("4px", "0"),
  },
  systemMessage: {
    justifySelf: "center",
    maxWidth: "80%",
    color: "#d7ebff",
    backgroundColor: "rgba(108, 182, 255, 0.08)",
    border: "1px solid rgba(108, 182, 255, 0.12)",
    ...shorthands.borderRadius("16px"),
    ...shorthands.padding("12px", "14px"),
    fontSize: "13px",
    textAlign: "center",
  },
  recoveryBanner: {
    justifySelf: "stretch",
    display: "grid",
    gap: "10px",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    boxShadow: "0 18px 40px rgba(0, 0, 0, 0.24)",
    ...shorthands.borderRadius("20px"),
    ...shorthands.padding("16px", "18px"),
  },
  recoveryBannerSyncing: {
    background:
      "linear-gradient(135deg, rgba(62, 129, 255, 0.18), rgba(25, 41, 74, 0.92) 45%, rgba(10, 17, 31, 0.96))",
  },
  recoveryBannerError: {
    background:
      "linear-gradient(135deg, rgba(196, 93, 70, 0.24), rgba(68, 23, 28, 0.92) 45%, rgba(22, 10, 14, 0.96))",
  },
  recoveryBannerBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    width: "fit-content",
    color: "#f3f8ff",
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    border: "1px solid rgba(255, 255, 255, 0.12)",
    ...shorthands.borderRadius("999px"),
    ...shorthands.padding("6px", "10px"),
    fontSize: "11px",
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  recoveryBannerAlert: {
    width: "16px",
    height: "16px",
    display: "inline-grid",
    placeItems: "center",
    color: "#fff7f5",
    backgroundColor: "rgba(255, 255, 255, 0.14)",
    ...shorthands.borderRadius("999px"),
    fontSize: "11px",
    fontWeight: 800,
  },
  recoveryBannerBody: {
    display: "grid",
    gap: "6px",
  },
  recoveryBannerMessage: {
    color: "#f4f8ff",
    fontSize: "15px",
    fontWeight: 680,
    letterSpacing: "-0.02em",
  },
  recoveryBannerDetail: {
    color: "#c9d8ee",
    fontSize: "13px",
    lineHeight: 1.5,
  },
  bubble: {
    display: "grid",
    gridTemplateColumns: "42px minmax(0, 1fr)",
    gap: "14px",
  },
  bubbleCard: {
    border: "1px solid rgba(255, 255, 255, 0.06)",
    background: "linear-gradient(180deg, rgba(255, 255, 255, 0.04), rgba(255, 255, 255, 0.025))",
    contain: "layout paint",
    ...shorthands.borderRadius("22px"),
    ...shorthands.padding("18px"),
  },
  bubbleHeader: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "10px",
    marginBottom: "10px",
  },
  rolePill: {
    display: "inline-flex",
    alignItems: "center",
    ...shorthands.borderRadius("999px"),
    ...shorthands.padding("4px", "10px"),
    fontSize: "11px",
    fontWeight: 650,
  },
  messageTime: { marginLeft: "auto", color: "#7c90b2", fontSize: "12px" },
  bubbleText: {
    whiteSpace: "pre-wrap",
    lineHeight: 1.7,
    color: "#dbe7fb",
    fontSize: "14px",
    wordBreak: "break-word",
  },
  bubbleCollapsed: {
    maxHeight: "200px",
    overflow: "hidden",
    maskImage: "linear-gradient(to bottom, black 65%, transparent 100%)",
    WebkitMaskImage: "linear-gradient(to bottom, black 65%, transparent 100%)",
  },
  expandButton: {
    marginTop: "10px",
    border: "none",
    background: "none",
    color: "#6cb6ff",
    cursor: "pointer",
    padding: 0,
    fontSize: "12px",
    fontWeight: 650,
  },
  thinkingCard: { borderLeftWidth: "3px", borderLeftStyle: "solid", opacity: 0.95 },
  thinkingDots: { display: "inline-flex", gap: "6px", color: "#a1b3d2" },

  /* ── Command Result Styles ────────────────────────────────── */
  commandResultBlock: {
    justifySelf: "center",
    maxWidth: "85%",
    display: "flex",
    flexDirection: "column" as const,
    gap: "4px",
    backgroundColor: "rgba(108, 182, 255, 0.05)",
    border: "1px solid rgba(108, 182, 255, 0.1)",
    ...shorthands.borderRadius("12px"),
    ...shorthands.padding("8px", "12px"),
    fontSize: "12px",
  },
  commandResultItem: {
    cursor: "pointer",
    ...shorthands.borderRadius("6px"),
    "&[open]": {
      backgroundColor: "rgba(255, 255, 255, 0.03)",
    },
  },
  commandResultSummary: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    listStyle: "none",
    ...shorthands.padding("4px", "6px"),
    ...shorthands.borderRadius("6px"),
    "&::-webkit-details-marker": { display: "none" },
    "&:hover": { backgroundColor: "rgba(255, 255, 255, 0.05)" },
  },
  commandStatusOk: { fontSize: "13px" },
  commandStatusErr: { fontSize: "13px" },
  commandName: {
    fontFamily: "monospace",
    fontWeight: 600,
    color: "#c3e4ff",
    fontSize: "12px",
  },
  commandError: {
    color: "#f87171",
    fontSize: "11px",
    marginLeft: "auto",
    fontStyle: "italic",
  },
  commandDetail: {
    margin: 0,
    ...shorthands.padding("6px", "10px"),
    fontSize: "11px",
    color: "#8da3c1",
    backgroundColor: "rgba(0, 0, 0, 0.15)",
    ...shorthands.borderRadius("6px"),
    overflowX: "auto" as const,
    maxHeight: "120px",
    whiteSpace: "pre-wrap" as const,
    wordBreak: "break-word" as const,
  },

  /* ── Filter Menu ────────────────────────────────────────── */
  chatHeader: {
    display: "flex",
    justifyContent: "flex-end",
    ...shorthands.padding("4px", "8px"),
    flexShrink: 0,
  },
  filterMenuButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "12px",
    color: "#8da3c1",
  },
  filterBadge: {
    minWidth: "16px",
    height: "16px",
    fontSize: "10px",
  },
  statusBar: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    color: "#c3e4ff",
    backgroundColor: "rgba(108, 182, 255, 0.08)",
    border: "1px solid rgba(108, 182, 255, 0.12)",
    ...shorthands.borderRadius("18px"),
    ...shorthands.padding("14px", "18px"),
    fontSize: "12px",
  },
  statusIndicator: {
    width: "10px",
    height: "10px",
    ...shorthands.borderRadius("999px"),
  },
  composerShell: {
    border: "1px solid rgba(255, 255, 255, 0.06)",
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    ...shorthands.borderRadius("22px"),
    ...shorthands.padding("16px"),
  },
  composerLabel: {
    marginBottom: "10px",
    color: "#7c90b2",
    fontSize: "11px",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  composerField: { width: "100%" },
  composerActions: {
    marginTop: "14px",
    display: "flex",
    justifyContent: "flex-end",
    gap: "10px",
  },
  emptyState: { color: "#a1b3d2" },
});
