import { makeStyles, shorthands } from "@fluentui/react-components";

export const useDmPanelStyles = makeStyles({
  root: {
    display: "flex",
    height: "100%",
    overflow: "hidden",
  },
  sidebar: {
    width: "220px",
    minWidth: "220px",
    borderRight: "1px solid var(--aa-border)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    background: "var(--aa-panel)",
  },
  sidebarHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    ...shorthands.padding("8px", "12px"),
    borderBottom: "1px solid var(--aa-border)",
  },
  threadList: {
    flex: 1,
    overflowY: "auto",
    ...shorthands.padding("4px", "0"),
  },
  threadItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    ...shorthands.padding("8px", "12px"),
    cursor: "pointer",
    border: "none",
    background: "transparent",
    width: "100%",
    textAlign: "left",
    color: "inherit",
    transitionProperty: "background",
    transitionDuration: "0.1s",
    "&:hover": {
      background: "rgba(91, 141, 239, 0.06)",
    },
  },
  threadItemSelected: {
    background: "rgba(91, 141, 239, 0.12)",
  },
  threadInfo: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: "2px",
  },
  threadNameRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  threadPreview: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "var(--aa-soft)",
    fontSize: "10px",
  },
  threadTime: {
    fontSize: "10px",
    color: "var(--aa-soft)",
    whiteSpace: "nowrap",
    fontFamily: "var(--mono)",
  },
  chatArea: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  chatHeader: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    ...shorthands.padding("8px", "16px"),
    borderBottom: "1px solid var(--aa-border)",
  },
  messageList: {
    flex: 1,
    overflowY: "auto",
    ...shorthands.padding("14px", "20px"),
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  msgRow: {
    display: "flex",
    gap: "10px",
    maxWidth: "85%",
  },
  msgRowHuman: {
    alignSelf: "flex-end",
    flexDirection: "row-reverse",
  },
  msgBubble: {
    ...shorthands.padding("8px", "12px"),
    ...shorthands.borderRadius("8px"),
    backgroundColor: "var(--aa-panel)",
    border: "1px solid var(--aa-border)",
    maxWidth: "100%",
  },
  msgBubbleHuman: {
    backgroundColor: "rgba(91, 141, 239, 0.15)",
    ...shorthands.borderColor("rgba(91, 141, 239, 0.3)"),
    color: "var(--aa-text)",
  },
  msgBubbleConsultant: {
    backgroundColor: "rgba(224, 151, 110, 0.15)",
    ...shorthands.borderColor("rgba(224, 151, 110, 0.3)"),
    color: "var(--aa-text)",
  },
  msgMeta: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    marginBottom: "2px",
  },
  msgTime: {
    fontSize: "10px",
    color: "var(--aa-soft)",
    fontFamily: "var(--mono)",
    marginTop: "4px",
  },
  msgTimeHuman: {
    textAlign: "right",
    color: "var(--aa-soft)",
  },
  msgContent: {
    fontFamily: "var(--mono)",
    fontSize: "13px",
    lineHeight: 1.6,
    "& p": { margin: 0 },
    "& pre": {
      backgroundColor: "var(--aa-bg)",
      ...shorthands.padding("8px"),
      ...shorthands.borderRadius("4px"),
      overflowX: "auto",
      fontSize: "12px",
    },
    "& code": {
      fontSize: "12px",
    },
  },
  composer: {
    borderTop: "1px solid var(--aa-border)",
    background: "var(--aa-panel)",
    ...shorthands.padding("10px", "16px"),
    display: "flex",
    gap: "8px",
    alignItems: "flex-end",
  },
  composerInput: {
    flex: 1,
  },
  emptyState: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    gap: "12px",
    color: "var(--aa-soft)",
    ...shorthands.padding("24px"),
    textAlign: "center",
  },
  emptyIcon: {
    fontSize: "26px",
    opacity: 0.5,
  },
  rolePill: {
    fontFamily: "var(--mono)",
    fontSize: "9px",
    fontWeight: 600,
    ...shorthands.borderRadius("3px"),
    ...shorthands.padding("3px", "6px", "2px"),
    textTransform: "uppercase",
    lineHeight: "1",
  },
  agentDropdown: {
    position: "absolute",
    top: "100%",
    right: 0,
    zIndex: 100,
    backgroundColor: "var(--aa-panel-alt)",
    border: "1px solid var(--aa-border)",
    ...shorthands.borderRadius("6px"),
    boxShadow: "var(--aa-shadow)",
    minWidth: "200px",
    ...shorthands.padding("4px", "0"),
    marginTop: "4px",
  },
  agentOption: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    ...shorthands.padding("8px", "12px"),
    cursor: "pointer",
    border: "none",
    background: "transparent",
    width: "100%",
    textAlign: "left",
    color: "inherit",
    "&:hover": {
      background: "rgba(91, 141, 239, 0.06)",
    },
  },
  newMsgWrapper: {
    position: "relative",
  },
  limitedModeNotice: {
    borderTop: "1px solid var(--aa-border)",
    ...shorthands.padding("12px", "16px"),
    color: "var(--aa-gold)",
    backgroundColor: "rgba(255, 152, 0, 0.06)",
    fontSize: "12px",
    lineHeight: 1.6,
  },
  avatar: {
    display: "grid",
    placeItems: "center",
    borderRadius: "50%",
    fontFamily: "var(--mono)",
    fontWeight: 700,
    color: "white",
    flexShrink: 0,
  },
  avatarSm: { width: "28px", height: "28px", fontSize: "9px" },
  avatarMd: { width: "32px", height: "32px", fontSize: "10px" },
  avatarLg: { width: "36px", height: "36px", fontSize: "11px" },
});
