import { makeStyles, shorthands } from "@fluentui/react-components";

export const useDigestPanelStyles = makeStyles({
  root: {
    display: "flex",
    flexDirection: "column",
    ...shorthands.gap("12px"),
    height: "100%",
    overflowY: "auto",
    ...shorthands.padding("16px"),
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    ...shorthands.gap("8px"),
  },
  headerLeft: {
    display: "flex",
    alignItems: "center",
    ...shorthands.gap("8px"),
  },
  controls: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    ...shorthands.gap("8px"),
  },
  select: {
    backgroundColor: "var(--aa-panel)",
    color: "var(--aa-text)",
    ...shorthands.border("1px", "solid", "var(--aa-border)"),
    ...shorthands.borderRadius("4px"),
    ...shorthands.padding("4px", "8px"),
    fontSize: "12px",
    fontFamily: "var(--aa-mono)",
    outline: "none",
    cursor: "pointer",
  },
  statsRow: {
    display: "flex",
    ...shorthands.gap("12px"),
    flexWrap: "wrap",
  },
  statCard: {
    display: "flex",
    flexDirection: "column",
    ...shorthands.gap("2px"),
    ...shorthands.padding("8px", "12px"),
    backgroundColor: "var(--aa-panel)",
    ...shorthands.border("1px", "solid", "var(--aa-border)"),
    ...shorthands.borderRadius("6px"),
    minWidth: "100px",
  },
  statValue: {
    fontFamily: "var(--aa-mono)",
    fontSize: "18px",
    fontWeight: 600,
    color: "var(--aa-text)",
  },
  statLabel: {
    fontSize: "10px",
    fontFamily: "var(--aa-mono)",
    color: "var(--aa-soft)",
    textTransform: "uppercase" as const,
    letterSpacing: "0.04em",
  },
  list: {
    display: "flex",
    flexDirection: "column",
    ...shorthands.gap("6px"),
  },
  row: {
    display: "flex",
    alignItems: "center",
    ...shorthands.gap("10px"),
    ...shorthands.padding("8px", "12px"),
    backgroundColor: "var(--aa-panel)",
    ...shorthands.border("1px", "solid", "var(--aa-border)"),
    ...shorthands.borderRadius("6px"),
    cursor: "pointer",
    transitionProperty: "background-color",
    transitionDuration: "0.15s",
    "&:hover": {
      backgroundColor: "rgba(91, 141, 239, 0.06)",
    },
  },
  rowActive: {
    backgroundColor: "rgba(91, 141, 239, 0.1)",
    ...shorthands.borderColor("var(--aa-cyan)"),
  },
  rowSummary: {
    flex: 1,
    fontSize: "12px",
    fontFamily: "var(--aa-mono)",
    color: "var(--aa-text)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  rowMeta: {
    display: "flex",
    alignItems: "center",
    ...shorthands.gap("8px"),
    flexShrink: 0,
  },
  rowMetaText: {
    fontSize: "10px",
    fontFamily: "var(--aa-mono)",
    color: "var(--aa-soft)",
    whiteSpace: "nowrap",
  },
  detail: {
    display: "flex",
    flexDirection: "column",
    ...shorthands.gap("10px"),
    ...shorthands.padding("12px"),
    backgroundColor: "var(--aa-panel)",
    ...shorthands.border("1px", "solid", "var(--aa-border)"),
    ...shorthands.borderRadius("6px"),
  },
  detailHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    ...shorthands.gap("8px"),
  },
  detailSummary: {
    fontSize: "13px",
    fontFamily: "var(--aa-mono)",
    color: "var(--aa-text)",
    lineHeight: "1.5",
    whiteSpace: "pre-wrap",
  },
  detailMetaRow: {
    display: "flex",
    ...shorthands.gap("16px"),
    flexWrap: "wrap",
  },
  detailMeta: {
    fontSize: "11px",
    fontFamily: "var(--aa-mono)",
    color: "var(--aa-soft)",
  },
  sourcesHeader: {
    fontSize: "11px",
    fontFamily: "var(--aa-mono)",
    fontWeight: 600,
    color: "var(--aa-soft)",
    textTransform: "uppercase" as const,
    letterSpacing: "0.04em",
    ...shorthands.margin("4px", "0"),
  },
  sourceCard: {
    display: "flex",
    flexDirection: "column",
    ...shorthands.gap("4px"),
    ...shorthands.padding("8px", "10px"),
    backgroundColor: "rgba(0, 0, 0, 0.15)",
    ...shorthands.borderRadius("4px"),
    ...shorthands.border("1px", "solid", "rgba(255,255,255,0.04)"),
  },
  sourceMetaRow: {
    display: "flex",
    ...shorthands.gap("8px"),
    fontSize: "10px",
    fontFamily: "var(--aa-mono)",
    color: "var(--aa-soft)",
  },
  sourceTaskLink: {
    cursor: "pointer",
    color: "var(--aa-cyan, #5b8def)",
    "&:hover": {
      textDecoration: "underline",
    },
  },
  sourceContent: {
    fontSize: "12px",
    fontFamily: "var(--aa-mono)",
    color: "var(--aa-text)",
    lineHeight: "1.5",
    whiteSpace: "pre-wrap",
  },
  pagination: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    ...shorthands.gap("8px"),
    ...shorthands.padding("8px", "0"),
  },
  paginationText: {
    fontSize: "11px",
    fontFamily: "var(--aa-mono)",
    color: "var(--aa-soft)",
  },
});
