import { makeStyles, shorthands } from "@fluentui/react-components";

export const useChatStyles = makeStyles({
  conversationLayout: {
    minHeight: 0,
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr) auto auto",
    gap: "0",
  },
  messageList: {
    minHeight: 0,
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    ...shorthands.padding("14px", "20px"),
  },
  systemMessage: {
    fontFamily: "var(--mono)",
    fontSize: "11px",
    color: "var(--aa-soft)",
    fontStyle: "italic",
    ...shorthands.padding("5px", "12px"),
    ...shorthands.borderRadius("6px"),
    background: "var(--aa-panel-alt)",
    textAlign: "center",
    maxWidth: "80%",
    alignSelf: "center",
  },
  bubble: {
    display: "flex",
    flexDirection: "column",
    gap: "0",
    background: "var(--aa-panel)",
    border: "1px solid var(--aa-border)",
    ...shorthands.borderRadius("8px"),
    ...shorthands.padding("12px", "14px"),
  },
  bubbleCard: {
    flex: 1,
    minWidth: 0,
    background: "transparent",
    border: "none",
    boxShadow: "none",
    ...shorthands.padding("0"),
    ...shorthands.borderRadius("0"),
  },
  bubbleHeader: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginBottom: "6px",
  },
  rolePill: {
    display: "inline-flex",
    alignItems: "center",
    fontFamily: "var(--mono)",
    ...shorthands.borderRadius("3px"),
    ...shorthands.padding("3px", "6px", "2px"),
    fontSize: "9px",
    lineHeight: "1",
    fontWeight: 600,
    textTransform: "uppercase",
  },
  messageTime: {
    marginLeft: "auto",
    color: "var(--aa-soft)",
    fontFamily: "var(--mono)",
    fontSize: "10px",
  },
  bubbleText: {
    whiteSpace: "pre-wrap",
    lineHeight: 1.6,
    color: "var(--aa-text)",
    fontFamily: "var(--mono)",
    fontSize: "13px",
    wordBreak: "break-word",
  },
  bubbleCollapsed: {
    maxHeight: "160px",
    overflow: "hidden",
    maskImage: "linear-gradient(to bottom, black 65%, transparent 100%)",
    WebkitMaskImage: "linear-gradient(to bottom, black 65%, transparent 100%)",
  },
  expandButton: {
    marginTop: "4px",
    border: "none",
    background: "none",
    color: "var(--aa-cyan)",
    cursor: "pointer",
    padding: 0,
    fontSize: "11px",
    fontWeight: 600,
  },
  thinkingCard: {
    borderLeftWidth: "2px",
    borderLeftStyle: "solid",
    borderLeftColor: "var(--aa-cyan)",
    opacity: 0.95,
  },
  thinkingDots: { display: "inline-flex", gap: "3px", color: "var(--aa-soft)", fontSize: "12px" },
  commandResultBlock: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "2px",
    background: "rgba(0, 150, 136, 0.08)",
    borderLeft: "3px solid var(--tool)",
    ...shorthands.borderRadius("0", "6px", "6px", "0"),
    ...shorthands.padding("6px", "12px"),
    fontSize: "11px",
    fontFamily: "var(--mono)",
  },
  commandResultItem: {
    cursor: "pointer",
    ...shorthands.borderRadius("4px"),
    "&[open]": {
      backgroundColor: "rgba(255, 255, 255, 0.02)",
    },
  },
  commandResultSummary: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    listStyle: "none",
    ...shorthands.padding("2px", "6px"),
    ...shorthands.borderRadius("4px"),
    "&::-webkit-details-marker": { display: "none" },
    "&:hover": { backgroundColor: "rgba(255, 255, 255, 0.03)" },
  },
  commandStatusOk: { fontSize: "12px" },
  commandStatusErr: { fontSize: "12px" },
  commandName: {
    fontFamily: "var(--mono)",
    fontWeight: 600,
    color: "var(--tool)",
    fontSize: "11px",
  },
  commandError: {
    color: "var(--error)",
    fontSize: "10px",
    marginLeft: "auto",
    fontStyle: "italic",
  },
  commandDetail: {
    margin: 0,
    ...shorthands.padding("4px", "10px"),
    fontSize: "10px",
    color: "var(--aa-soft)",
    backgroundColor: "rgba(0, 0, 0, 0.2)",
    ...shorthands.borderRadius("4px"),
    overflowX: "auto" as const,
    maxHeight: "100px",
    whiteSpace: "pre-wrap" as const,
    wordBreak: "break-word" as const,
  },
  chatHeader: {
    display: "flex",
    justifyContent: "flex-end",
    ...shorthands.padding("4px", "8px"),
    flexShrink: 0,
  },
  statusBar: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    color: "var(--aa-soft)",
    backgroundColor: "rgba(91, 141, 239, 0.04)",
    border: "1px solid var(--aa-border)",
    ...shorthands.borderRadius("4px"),
    ...shorthands.padding("4px", "10px"),
    fontSize: "11px",
    fontFamily: "var(--mono)",
  },
  statusIndicator: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "14px",
    height: "14px",
    ...shorthands.borderRadius("999px"),
    fontSize: "10px",
    flexShrink: 0,
  },
  composerShell: {
    borderTop: "1px solid var(--aa-border)",
    background: "var(--aa-panel)",
    ...shorthands.borderRadius("0"),
    ...shorthands.padding("10px", "16px"),
  },
  composerLabel: {
    marginBottom: "4px",
    color: "var(--aa-soft)",
    fontFamily: "var(--mono)",
    fontSize: "10px",
  },
  composerField: { width: "100%" },
  composerActions: {
    marginTop: "8px",
    display: "flex",
    justifyContent: "flex-end",
    gap: "8px",
  },
  emptyState: { color: "var(--aa-soft)" },
});
