import { makeStyles, shorthands, tokens } from "@fluentui/react-components";

export const useSidebarStyles = makeStyles({
  sidebar: {
    width: "var(--sidebar-width)",
    minWidth: "var(--sidebar-width)",
    height: "100%",
    background: "var(--aa-panel)",
    borderRight: "1px solid var(--aa-border)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    position: "relative",
  },
  sidebarCollapsed: {
    width: "48px",
    minWidth: "48px",
  },
  sidebarHeader: {
    borderBottom: "1px solid var(--aa-border)",
    ...shorthands.padding("10px", "14px", "12px"),
  },
  sidebarToolbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: tokens.spacingHorizontalS,
  },
  brandBlock: {
    display: "grid",
    gap: "2px",
  },
  appTitle: {
    fontFamily: "var(--sans)",
    fontSize: "14px",
    fontWeight: 700,
    letterSpacing: "-0.02em",
    color: "var(--aa-text-strong)",
    lineHeight: 1.2,
  },
  appSubtitle: {
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    fontFamily: "var(--mono)",
    fontSize: "10px",
    color: "var(--aa-lime)",
  },
  eyebrow: {
    display: "inline-flex",
    alignItems: "center",
    width: "fit-content",
    gap: "4px",
    color: "var(--aa-lime)",
    fontSize: "10px",
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  sidebarBody: { flex: 1, overflowY: "auto", paddingBottom: "8px" },
  section: {
    ...shorthands.padding("4px", "8px"),
  },
  sectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: tokens.spacingHorizontalS,
    ...shorthands.padding("10px", "10px", "3px"),
  },
  sectionCount: {
    fontFamily: "var(--mono)",
    fontSize: "9px",
    fontWeight: 500,
    color: "var(--aa-cyan)",
    backgroundColor: "rgba(91, 141, 239, 0.12)",
    ...shorthands.borderRadius("3px"),
    ...shorthands.padding("1px", "5px"),
  },
  sectionLabel: {
    color: "var(--aa-soft)",
    fontSize: "10px",
    fontWeight: 600,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  roomList: { display: "grid", gap: "1px" },
  roomListScrollable: {
    display: "grid",
    gap: "1px",
    // Cap to roughly 10 simple room rows (≈22px each + 1px gap) so a long
    // room list doesn't push the Agents section off-screen. Falls back to
    // 40vh on small viewports so the cap stays within reach.
    maxHeight: "min(280px, 40vh)",
    overflowY: "auto",
    overflowX: "hidden",
  },
  sidebarResizeHandle: {
    position: "absolute",
    top: 0,
    right: 0,
    width: "5px",
    height: "100%",
    cursor: "col-resize",
    userSelect: "none",
    zIndex: 10,
    backgroundColor: "transparent",
    transitionProperty: "background-color",
    transitionDuration: "0.15s",
    ":hover": {
      backgroundColor: "rgba(91, 141, 239, 0.35)",
    },
  },
  sidebarResizeHandleActive: {
    backgroundColor: "rgba(91, 141, 239, 0.55)",
  },
  sidebarUtilityRow: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
  },
  sidebarIconButton: {
    minWidth: "24px",
    width: "24px",
    height: "24px",
    color: "var(--aa-soft)",
    backgroundColor: "transparent",
    border: "none",
    ":hover": {
      backgroundColor: "rgba(91, 141, 239, 0.06)",
      color: "var(--aa-text)",
    },
  },
  sidebarProjectCard: {
    ...shorthands.padding("6px", "0", "0"),
  },
  sidebarProjectLabel: {
    color: "var(--aa-soft)",
    fontSize: "10px",
    fontWeight: 600,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  sidebarProjectRow: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  sidebarProjectIcon: {
    width: "20px",
    height: "20px",
    display: "grid",
    placeItems: "center",
    fontSize: "12px",
  },
  sidebarProjectName: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "var(--aa-text)",
    fontSize: "11px",
    fontWeight: 500,
    flex: 1,
    minWidth: 0,
  },
  sidebarProjectPath: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "var(--aa-soft)",
    fontSize: "10px",
  },
  sidebarProjectAction: {
    minWidth: "auto",
    height: "24px",
    color: "var(--aa-soft)",
  },
  sidebarSnapshotGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: "6px",
  },
  sidebarSnapshotCard: {
    display: "grid",
    gap: "2px",
    ...shorthands.padding("4px"),
  },
  sidebarSnapshotValue: {
    color: "var(--aa-text-strong)",
    fontSize: "14px",
    fontWeight: 700,
  },
  sidebarSnapshotLabel: {
    color: "var(--aa-soft)",
    fontSize: "9px",
    fontWeight: 600,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  sprintIndicator: {
    ...shorthands.padding("6px", "12px"),
    fontSize: "11px",
    fontWeight: 600,
    letterSpacing: "0.04em",
    color: "var(--aa-lime, #a3e635)",
    textTransform: "uppercase",
  },
  navSection: {
    ...shorthands.padding("4px", "8px"),
  },
  navGroup: {
    ...shorthands.margin("2px", "0"),
  },
  navGroupHeader: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    width: "100%",
    ...shorthands.padding("4px", "8px"),
    ...shorthands.borderRadius("4px"),
    color: "var(--aa-soft)",
    fontSize: "9px",
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    border: "none",
    background: "transparent",
    textAlign: "left",
    cursor: "pointer",
    transitionProperty: "color, background",
    transitionDuration: "0.12s",
    ":hover": {
      color: "var(--aa-muted)",
      background: "rgba(91, 141, 239, 0.04)",
    },
  },
  navGroupChevron: {
    display: "inline-block",
    width: "10px",
    fontSize: "9px",
    color: "var(--aa-soft)",
    flexShrink: 0,
  },
  navGroupLabel: {
    flexGrow: 1,
  },
  navGroupActiveDot: {
    display: "inline-block",
    width: "6px",
    height: "6px",
    ...shorthands.borderRadius("50%"),
    background: "var(--aa-cyan)",
    flexShrink: 0,
  },
  navItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    width: "100%",
    ...shorthands.padding("6px", "10px"),
    ...shorthands.borderRadius("6px"),
    color: "var(--aa-soft)",
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: "14px",
    border: "none",
    background: "transparent",
    textAlign: "left",
    borderLeft: "2px solid transparent",
    cursor: "pointer",
    transitionProperty: "all",
    transitionDuration: "0.12s",
    ":hover": {
      color: "var(--aa-muted)",
      background: "rgba(91, 141, 239, 0.06)",
    },
  },
  navItemActive: {
    color: "var(--aa-cyan)",
    background: "rgba(91, 141, 239, 0.12)",
    borderLeftColor: "var(--aa-cyan)",
  },
  navIcon: {
    width: "16px",
    textAlign: "center",
    fontSize: "13px",
    flexShrink: 0,
  },
  roomButton: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: "7px",
    border: "none",
    background: "transparent",
    color: "var(--aa-muted)",
    cursor: "pointer",
    textAlign: "left",
    ...shorthands.borderRadius("5px"),
    ...shorthands.padding("4px", "10px"),
    fontSize: "11px",
    lineHeight: "14px",
    transitionProperty: "all",
    transitionDuration: "0.12s",
  },
  roomButtonHover: {
    ":hover": {
      background: "rgba(91, 141, 239, 0.06)",
      color: "var(--aa-text)",
    },
  },
  roomButtonActive: {
    background: "rgba(91, 141, 239, 0.12)",
    color: "var(--aa-text-strong)",
  },
  roomButtonIcon: {
    display: "none",
  },
  roomButtonName: {
    fontSize: "11px",
    fontWeight: 500,
    color: "inherit",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    flex: 1,
    minWidth: 0,
  },
  roomButtonBody: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    minWidth: 0,
    flex: 1,
  },
  roomButtonTopRow: {
    display: "none",
  },
  roomButtonMeta: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
  },
  roomPhaseLabel: {
    display: "none",
  },
  roomButtonCount: {
    marginLeft: "auto",
    fontFamily: "var(--mono)",
    fontSize: "9px",
    fontWeight: 500,
    color: "var(--aa-cyan)",
    backgroundColor: "rgba(91, 141, 239, 0.12)",
    ...shorthands.borderRadius("3px"),
    ...shorthands.padding("1px", "5px"),
    letterSpacing: "0.03em",
    textTransform: "uppercase",
    flexShrink: 0,
  },
  roomButtonTitleWrap: {
    minWidth: 0,
    flex: 1,
  },
  roomButtonTask: {
    display: "none",
  },
  roomPhaseDot: {
    width: "6px",
    height: "6px",
    ...shorthands.borderRadius("50%"),
    flexShrink: 0,
  },
  compactSidebar: {
    flex: 1,
    display: "grid",
    alignContent: "start",
    gap: "8px",
    ...shorthands.padding("8px", "4px"),
  },
  compactSidebarMarker: {
    width: "100%",
    height: "32px",
    display: "grid",
    placeItems: "center",
    color: "var(--aa-text)",
    fontSize: "10px",
    fontWeight: 700,
  },
  compactButton: {
    position: "relative" as const,
    width: "100%",
    height: "36px",
    border: "none",
    background: "transparent",
    color: "var(--aa-muted)",
    cursor: "pointer",
    fontWeight: 600,
    fontSize: "10px",
    ...shorthands.borderRadius("6px"),
    ":hover": {
      background: "rgba(91, 141, 239, 0.06)",
      color: "var(--aa-text)",
    },
  },
  compactButtonActive: {
    background: "rgba(91, 141, 239, 0.12)",
    color: "var(--aa-text-strong)",
  },
  compactRoomDot: {
    position: "absolute" as const,
    top: "4px",
    right: "4px",
    width: "5px",
    height: "5px",
    ...shorthands.borderRadius("50%"),
  },
  sidebarRoomHeader: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    ...shorthands.padding("8px", "10px"),
    borderBottom: "1px solid var(--aa-border)",
    fontSize: "12px",
    fontWeight: 600,
    color: "var(--aa-text)",
  },
  sidebarRoomDot: {
    width: "6px",
    height: "6px",
    ...shorthands.borderRadius("999px"),
    flexShrink: 0,
  },
  agentListItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    ...shorthands.padding("4px", "10px"),
    fontSize: "11px",
    color: "var(--aa-muted)",
  },
  agentStateDot: {
    width: "6px",
    height: "6px",
    ...shorthands.borderRadius("999px"),
    flexShrink: 0,
  },
  roomAgentList: {
    display: "grid",
    gap: "1px",
    marginLeft: "14px",
    paddingLeft: "8px",
    paddingTop: "2px",
    paddingBottom: "4px",
    borderLeft: "1px solid var(--aa-border)",
  },
  roomAgentListSeparator: {
    height: "1px",
    background: "var(--aa-border)",
    marginLeft: "22px",
    marginRight: "8px",
    marginBottom: "2px",
    opacity: 0.6,
  },
  roomAgentItem: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "11px",
    color: "var(--aa-soft)",
  },
  workspaceButton: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: "7px",
    border: "none",
    background: "transparent",
    color: "var(--aa-muted)",
    cursor: "pointer",
    textAlign: "left",
    ...shorthands.borderRadius("5px"),
    ...shorthands.padding("4px", "10px"),
    fontSize: "11px",
    lineHeight: "14px",
    transitionProperty: "all",
    transitionDuration: "0.12s",
  },
  workspaceButtonBody: {
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    gap: "6px",
    flex: 1,
  },
  workspaceButtonTopRow: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    minWidth: 0,
    flex: 1,
  },
  workspaceIcon: {
    display: "none",
  },
  workspaceName: {
    fontSize: "11px",
    fontWeight: 500,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  workspaceRole: {
    display: "none",
  },
  workspaceStateBadge: {
    fontSize: "9px",
    fontWeight: 500,
    letterSpacing: "0.03em",
    ...shorthands.borderRadius("3px"),
    ...shorthands.padding("1px", "5px"),
    marginLeft: "auto",
    textTransform: "uppercase",
  },
  workspaceTask: {
    display: "none",
  },
  userArea: {
    borderTop: "1px solid var(--aa-border)",
    ...shorthands.padding("8px", "14px"),
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "11px",
    color: "var(--aa-soft)",
  },
  userAvatar: {
    width: "22px",
    height: "22px",
    ...shorthands.borderRadius("50%"),
    background: "linear-gradient(135deg, var(--aa-cyan), var(--special))",
    display: "grid",
    placeItems: "center",
    fontSize: "9px",
    fontWeight: 700,
    color: "white",
    flexShrink: 0,
  },
});
