import { makeStyles, shorthands } from "@fluentui/react-components";

export const useWorkspaceStyles = makeStyles({
  workspace: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    minWidth: 0,
  },
  headerDivider: {
    width: "1px",
    height: "16px",
    background: "var(--aa-border)",
    flexShrink: 0,
  },
  workspaceHeader: {
    height: "var(--topbar-height)",
    minHeight: "var(--topbar-height)",
    background: "var(--aa-panel)",
    borderBottom: "1px solid var(--aa-border)",
    display: "flex",
    alignItems: "center",
    ...shorthands.padding("0", "16px"),
    gap: "10px",
  },
  workspaceHeaderBody: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    minWidth: 0,
    flex: 1,
  },
  workspaceHeaderTopRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "10px",
    flex: 1,
    minWidth: 0,
  },
  workspaceHeaderSignals: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flexShrink: 0,
  },
  workspaceSignal: {
    display: "inline-flex",
    alignItems: "center",
    fontFamily: "var(--mono)",
    fontSize: "9px",
    fontWeight: 600,
    ...shorthands.borderRadius("4px"),
    ...shorthands.padding("2px", "7px"),
    backgroundColor: "rgba(91, 141, 239, 0.12)",
    color: "var(--aa-cyan)",
  },
  workspaceSignalWarning: {
    backgroundColor: "rgba(255, 152, 0, 0.12)",
    color: "var(--aa-gold)",
  },
  workspaceTitle: {
    fontSize: "14px",
    fontWeight: 600,
    color: "var(--aa-text-strong)",
    letterSpacing: "-0.01em",
    whiteSpace: "nowrap" as const,
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  workspaceSubtitle: {
    display: "none",
  },
  workspaceMetaRow: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    color: "var(--aa-soft)",
    fontFamily: "var(--mono)",
    fontSize: "10px",
  },
  workspaceMetaChip: {
    display: "none",
  },
  workspaceMetaSep: {
    color: "var(--aa-border)",
    userSelect: "none" as const,
  },
  workspaceMetaText: {
    color: "var(--aa-soft)",
    fontFamily: "var(--mono)",
    fontSize: "10px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  phasePill: {
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    fontFamily: "var(--mono)",
    fontSize: "9px",
    fontWeight: 600,
    color: "var(--aa-lime)",
    backgroundColor: "rgba(76, 175, 80, 0.12)",
    ...shorthands.borderRadius("4px"),
    ...shorthands.padding("2px", "7px"),
  },
  phasePillDot: {
    width: "5px",
    height: "5px",
    backgroundColor: "var(--aa-lime)",
    ...shorthands.borderRadius("50%"),
    animation: "aa-pulse 2s ease-in-out infinite",
  },
  limitedModeBanner: {
    display: "grid",
    gap: "8px",
    borderBottom: "1px solid var(--aa-border)",
    background: "rgba(255, 152, 0, 0.06)",
    ...shorthands.padding("12px", "16px"),
  },
  limitedModeBadge: {
    display: "inline-flex",
    alignItems: "center",
    width: "fit-content",
    fontFamily: "var(--mono)",
    fontSize: "10px",
    fontWeight: 600,
    color: "var(--aa-gold)",
    backgroundColor: "rgba(255, 152, 0, 0.12)",
    border: "1px solid rgba(255, 152, 0, 0.2)",
    ...shorthands.borderRadius("4px"),
    ...shorthands.padding("2px", "8px"),
    textTransform: "uppercase",
  },
  limitedModeTitle: {
    color: "var(--aa-text-strong)",
    fontSize: "13px",
    fontWeight: 600,
  },
  limitedModeDescription: {
    color: "var(--aa-muted)",
    fontSize: "12px",
    lineHeight: 1.5,
  },
  toolbarSelect: {
    ...shorthands.padding("3px", "8px"),
    ...shorthands.borderRadius("4px"),
    fontFamily: "var(--mono)",
    fontSize: "11px",
    background: "var(--aa-panel-alt)",
    border: "1px solid var(--aa-border)",
    color: "var(--aa-muted)",
    cursor: "pointer",
    ":focus": {
      ...shorthands.borderColor("var(--aa-cyan)"),
    },
  },
  tabBar: {
    height: "var(--toolbar-height)",
    minHeight: "var(--toolbar-height)",
    background: "var(--aa-bg)",
    borderBottom: "1px solid var(--aa-border)",
    display: "flex",
    alignItems: "center",
    ...shorthands.padding("0", "16px"),
    gap: "8px",
    fontSize: "11px",
  },
  tabList: {
    display: "flex",
    gap: "6px",
    alignItems: "center",
    "& [role=tab]": {
      display: "inline-flex",
      alignItems: "center",
      gap: "5px",
      minHeight: "26px",
      color: "var(--aa-muted)",
      backgroundColor: "transparent",
      border: "1px solid var(--aa-border)",
      ...shorthands.borderRadius("4px"),
      ...shorthands.padding("3px", "9px"),
      fontSize: "11px",
      fontWeight: 500,
      transitionProperty: "all",
      transitionDuration: "0.12s",
    },
    "& [role=tab]:hover": {
      ...shorthands.borderColor("var(--aa-border-strong)"),
      color: "var(--aa-text)",
      background: "rgba(91, 141, 239, 0.04)",
    },
    "& [role=tab][aria-selected=true]": {
      background: "rgba(91, 141, 239, 0.12)",
      color: "var(--aa-cyan)",
      ...shorthands.borderColor("rgba(91, 141, 239, 0.3)"),
    },
  },
  tabStrip: {
    display: "flex",
    gap: "6px",
    alignItems: "center",
    flex: 1,
    minWidth: 0,
  },
  tabLabelStack: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    minWidth: 0,
  },
  tabLabelTitle: {
    fontSize: "11px",
    fontWeight: 500,
    lineHeight: 1.2,
  },
  tabLabelDetail: {
    display: "none",
  },
  overflowTrigger: {
    display: "inline-flex",
    gap: "5px",
    alignItems: "center",
    minHeight: "26px",
    color: "var(--aa-soft)",
    backgroundColor: "transparent",
    border: "1px solid var(--aa-border)",
    ...shorthands.borderRadius("4px"),
    ...shorthands.padding("3px", "9px"),
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: "11px",
    fontWeight: 500,
    "&:hover": {
      ...shorthands.borderColor("var(--aa-border-strong)"),
      color: "var(--aa-text)",
      background: "rgba(91, 141, 239, 0.04)",
    },
  },
  overflowTriggerActive: {
    background: "rgba(91, 141, 239, 0.12)",
    color: "var(--aa-cyan)",
    ...shorthands.borderColor("rgba(91, 141, 239, 0.3)"),
  },
  overflowItemActive: {
    fontWeight: 700,
  },
  tabContent: {
    flex: 1,
    minHeight: 0,
    display: "grid",
    gridTemplateRows: "minmax(0, 1fr)",
    overflow: "auto",
    ...shorthands.padding("0"),
  },
  filterMenuButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    fontSize: "11px",
    color: "var(--aa-soft)",
  },
  filterBadge: {
    minWidth: "14px",
    height: "14px",
    fontSize: "9px",
  },
});
