import { makeStyles, shorthands } from "@fluentui/react-components";

export const useTaskDetailStyles = makeStyles({
  expandedSection: {
    marginTop: "14px",
    ...shorthands.padding("12px", "0", "0"),
    borderTop: "1px solid var(--aa-border)",
  },
  descriptionText: {
    fontSize: "13px",
    color: "var(--aa-soft)",
    lineHeight: 1.6,
    whiteSpace: "pre-wrap",
    marginBottom: "12px",
  },
  sectionLabel: {
    fontSize: "11px",
    fontWeight: 600,
    color: "var(--aa-muted)",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    marginBottom: "6px",
    marginTop: "12px",
  },
  actionBar: {
    display: "flex",
    gap: "8px",
    flexWrap: "wrap",
    marginTop: "14px",
    ...shorthands.padding("10px", "0", "0"),
    borderTop: "1px solid var(--aa-border)",
  },
  actionFeedback: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "12px",
    color: "var(--aa-soft)",
    marginTop: "8px",
  },
  actionError: {
    color: "var(--error)",
  },
  actionSuccess: {
    color: "var(--aa-lime)",
  },
  reasonArea: {
    marginTop: "10px",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  reasonActions: {
    display: "flex",
    gap: "6px",
    justifyContent: "flex-end",
  },
  commentsSection: {
    marginTop: "14px",
    ...shorthands.padding("10px", "0", "0"),
    borderTop: "1px solid var(--aa-border)",
  },
  commentCard: {
    ...shorthands.padding("8px", "10px"),
    marginBottom: "6px",
    ...shorthands.borderRadius("6px"),
    background: "rgba(255, 255, 255, 0.02)",
    border: "1px solid var(--aa-border)",
  },
  commentHeader: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    marginBottom: "4px",
    fontSize: "12px",
  },
  commentAuthor: {
    fontWeight: 600,
    color: "var(--aa-text-strong)",
  },
  commentTime: {
    color: "var(--aa-muted)",
    fontFamily: "var(--mono)",
    fontSize: "10px",
  },
  commentContent: {
    fontSize: "13px",
    color: "var(--aa-soft)",
    lineHeight: 1.5,
    whiteSpace: "pre-wrap",
  },
  reviewMeta: {
    display: "flex",
    gap: "12px",
    flexWrap: "wrap",
    marginTop: "8px",
    fontFamily: "var(--mono)",
    fontSize: "10px",
    color: "var(--aa-muted)",
  },
  specLinkRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    ...shorthands.padding("6px", "8px"),
    ...shorthands.borderRadius("4px"),
    background: "rgba(255, 255, 255, 0.02)",
    marginBottom: "4px",
    fontSize: "12px",
  },
  specLinkSection: {
    fontFamily: "var(--mono)",
    fontWeight: 600,
    color: "var(--aa-text-strong)",
    fontSize: "12px",
  },
  specLinkNote: {
    fontSize: "11px",
    color: "var(--aa-muted)",
    marginLeft: "auto",
  },
  evidenceTable: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "11px",
    fontFamily: "var(--mono)",
    marginTop: "6px",
  },
  evidenceTh: {
    textAlign: "left",
    ...shorthands.padding("4px", "8px"),
    borderBottom: "1px solid var(--aa-border)",
    color: "var(--aa-muted)",
    fontWeight: 600,
    fontSize: "10px",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  },
  evidenceTd: {
    ...shorthands.padding("4px", "8px"),
    borderBottom: "1px solid var(--aa-hairline)",
    color: "var(--aa-soft)",
    fontSize: "11px",
  },
  gateBox: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    ...shorthands.padding("8px", "10px"),
    ...shorthands.borderRadius("6px"),
    border: "1px solid var(--aa-border)",
    background: "rgba(255, 255, 255, 0.02)",
    marginTop: "6px",
    fontSize: "12px",
  },
  gateMetBorder: {
    ...shorthands.borderColor("rgba(76, 175, 80, 0.3)"),
  },
  gateNotMetBorder: {
    ...shorthands.borderColor("rgba(255, 152, 0, 0.3)"),
  },
  assignPicker: {
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
    marginTop: "8px",
  },
  assignPickerBtn: {
    cursor: "pointer",
    ...shorthands.padding("4px", "10px"),
    ...shorthands.borderRadius("4px"),
    fontSize: "12px",
    border: "1px solid var(--aa-border)",
    background: "transparent",
    color: "var(--aa-text)",
    transitionProperty: "background, border-color",
    transitionDuration: "0.15s",
    ":hover": {
      background: "var(--aa-border)",
    },
  },
});
