import { makeStyles, shorthands } from "@fluentui/react-components";

export const useSettingsStyles = makeStyles({
  sectionTitle: {
    fontSize: "13px",
    fontWeight: 600,
    color: "#e2e8f0",
    marginBottom: "20px",
    textTransform: "uppercase" as const,
    letterSpacing: "1px",
  },
  emptyState: {
    fontSize: "13px",
    color: "rgba(148,163,184,0.5)",
    ...shorthands.padding("20px"),
    textAlign: "center" as const,
    fontStyle: "italic",
  },
  fieldLabel: {
    fontSize: "11px",
    fontWeight: 600,
    color: "rgba(148,163,184,0.7)",
    textTransform: "uppercase" as const,
    letterSpacing: "0.8px",
    marginBottom: "4px",
  },
  fieldHint: {
    fontSize: "11px",
    color: "rgba(148,163,184,0.4)",
    marginTop: "4px",
  },
  inputField: {
    ...shorthands.padding("10px", "14px"),
    ...shorthands.borderRadius("8px"),
    border: "1px solid rgba(255,255,255,0.08)",
    background: "rgba(0,0,0,0.3)",
    color: "#e2e8f0",
    fontSize: "14px",
    fontFamily: "inherit",
    outline: "none",
    width: "100%",
    boxSizing: "border-box" as const,
  },
  textareaField: {
    ...shorthands.padding("12px", "14px"),
    ...shorthands.borderRadius("8px"),
    border: "1px solid rgba(255,255,255,0.08)",
    background: "rgba(0,0,0,0.3)",
    color: "#e2e8f0",
    fontSize: "13px",
    fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
    lineHeight: "1.6",
    outline: "none",
    width: "100%",
    boxSizing: "border-box" as const,
    resize: "vertical" as const,
    minHeight: "140px",
  },
  errorText: {
    fontSize: "13px",
    color: "#f87171",
    ...shorthands.padding("8px", "12px"),
    ...shorthands.borderRadius("6px"),
    background: "rgba(248,113,113,0.08)",
    border: "1px solid rgba(248,113,113,0.15)",
  },
});
