import { makeStyles, shorthands } from "@fluentui/react-components";

export const useProjectSelectorStyles = makeStyles({
  root: {
    position: "relative",
    minHeight: "100vh",
    overflow: "hidden",
    ...shorthands.padding("36px", "24px"),
  },
  backdrop: {
    position: "absolute",
    inset: 0,
    background:
      "radial-gradient(circle at 12% 16%, rgba(91, 141, 239, 0.16), transparent 24%), radial-gradient(circle at 86% 14%, rgba(156, 39, 176, 0.12), transparent 20%), radial-gradient(circle at 66% 84%, rgba(0, 150, 136, 0.12), transparent 26%)",
    pointerEvents: "none",
  },
  container: {
    position: "relative",
    width: "min(1240px, 100%)",
    minHeight: "calc(100vh - 72px)",
    margin: "0 auto",
    display: "grid",
    gridTemplateColumns: "minmax(320px, 0.86fr) minmax(0, 1.14fr)",
    gap: "28px",
    alignItems: "stretch",
    "@media (max-width: 1080px)": {
      gridTemplateColumns: "1fr",
    },
  },
  rail: {
    display: "grid",
    alignContent: "space-between",
    gap: "24px",
    border: "1px solid var(--aa-border)",
    background:
      "linear-gradient(180deg, rgba(13, 22, 37, 0.88), rgba(8, 14, 24, 0.96))",
    boxShadow: "0 32px 90px rgba(0, 0, 0, 0.34)",
    ...shorthands.borderRadius("32px"),
    ...shorthands.padding("34px"),
  },
  railHeader: {
    display: "grid",
    gap: "16px",
  },
  railKicker: {
    display: "inline-flex",
    alignItems: "center",
    width: "fit-content",
    color: "var(--aa-cyan)",
    backgroundColor: "rgba(91, 141, 239, 0.12)",
    border: "1px solid rgba(91, 141, 239, 0.22)",
    ...shorthands.borderRadius("999px"),
    ...shorthands.padding("8px", "14px"),
    fontSize: "11px",
    fontWeight: 700,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
  },
  railTitle: {
    margin: 0,
    color: "var(--aa-text-strong)",
    fontFamily: "var(--heading)",
    fontSize: "clamp(2.8rem, 5.5vw, 4.5rem)",
    lineHeight: 0.95,
    letterSpacing: "-0.05em",
  },
  railBody: {
    margin: 0,
    color: "var(--aa-muted)",
    fontSize: "16px",
    lineHeight: 1.8,
    maxWidth: "38rem",
  },
  railGrid: {
    display: "grid",
    gap: "14px",
  },
  railCard: {
    display: "grid",
    gap: "10px",
    border: "1px solid var(--aa-hairline)",
    background: "linear-gradient(180deg, rgba(255, 255, 255, 0.04), rgba(255, 255, 255, 0.02))",
    ...shorthands.borderRadius("24px"),
    ...shorthands.padding("18px"),
  },
  railCardLabel: {
    color: "var(--aa-cyan)",
    fontSize: "11px",
    fontWeight: 700,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
  },
  railCardValue: {
    color: "var(--aa-text-strong)",
    fontSize: "18px",
    fontWeight: 700,
  },
  railCardBody: {
    color: "var(--aa-soft)",
    fontSize: "13px",
    lineHeight: 1.7,
  },
  railFootnote: {
    color: "var(--aa-soft)",
    fontSize: "12px",
    lineHeight: 1.8,
  },
  deck: {
    display: "grid",
    gridTemplateRows: "auto auto minmax(0, 1fr)",
    gap: "18px",
    border: "1px solid var(--aa-border)",
    background:
      "linear-gradient(180deg, rgba(18, 30, 48, 0.92), rgba(9, 15, 25, 0.98))",
    boxShadow: "0 32px 90px rgba(0, 0, 0, 0.38)",
    ...shorthands.borderRadius("32px"),
    ...shorthands.padding("28px"),
  },
  deckTop: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: "18px",
    "@media (max-width: 780px)": {
      flexDirection: "column",
    },
  },
  userWrap: {
    display: "flex",
    justifyContent: "flex-end",
  },
  deckHeader: {
    display: "grid",
    gap: "8px",
    maxWidth: "44rem",
  },
  deckKicker: {
    color: "var(--aa-cyan)",
    fontSize: "11px",
    fontWeight: 700,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
  },
  deckTitle: {
    color: "var(--aa-text-strong)",
    fontFamily: "var(--heading)",
    fontSize: "clamp(2.1rem, 4vw, 3.1rem)",
    lineHeight: 1,
    letterSpacing: "-0.05em",
  },
  deckDescription: {
    color: "var(--aa-muted)",
    fontSize: "15px",
    lineHeight: 1.8,
  },
  tabList: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: "10px",
  },
  panel: {
    minHeight: 0,
    border: "1px solid var(--aa-border)",
    background: "linear-gradient(180deg, rgba(8, 13, 23, 0.78), rgba(10, 18, 30, 0.92))",
    ...shorthands.borderRadius("28px"),
    ...shorthands.padding("24px"),
  },
  placeholder: {
    display: "grid",
    placeItems: "center",
    minHeight: "180px",
    color: "var(--aa-soft)",
    fontSize: "14px",
  },
  loadingWrap: {
    display: "grid",
    placeItems: "center",
    gap: "12px",
    minHeight: "180px",
  },
  workspaceList: { display: "grid", gap: "12px" },
  workspaceCard: {
    width: "100%",
    display: "grid",
    gridTemplateColumns: "52px 1fr auto",
    gap: "16px",
    alignItems: "center",
    border: "1px solid var(--aa-hairline)",
    background: "linear-gradient(180deg, rgba(255, 255, 255, 0.03), rgba(255, 255, 255, 0.02))",
    color: "inherit",
    cursor: "pointer",
    textAlign: "left",
    boxShadow: "0 18px 40px rgba(0, 0, 0, 0.18)",
    transitionDuration: "160ms",
    transitionProperty: "transform, border-color, background-color",
    ...shorthands.borderRadius("22px"),
    ...shorthands.padding("16px"),
    ":hover": {
      transform: "translateY(-1px)",
      border: "1px solid rgba(91, 141, 239, 0.22)",
      background: "linear-gradient(180deg, rgba(91, 141, 239, 0.06), rgba(255, 255, 255, 0.03))",
    },
  },
  workspaceIcon: {
    width: "52px",
    height: "52px",
    display: "grid",
    placeItems: "center",
    color: "var(--aa-bg)",
    fontSize: "18px",
    fontWeight: 800,
    background: "linear-gradient(145deg, var(--aa-gold), var(--aa-cyan))",
    boxShadow: "0 12px 32px rgba(0, 0, 0, 0.22)",
    ...shorthands.borderRadius("18px"),
  },
  workspaceName: { color: "var(--aa-text-strong)", fontSize: "15px", fontWeight: 700 },
  workspacePath: {
    marginTop: "4px",
    color: "var(--aa-soft)",
    fontSize: "12px",
    lineHeight: 1.6,
    overflowWrap: "anywhere",
  },
  workspaceMeta: {
    color: "var(--aa-soft)",
    fontSize: "12px",
    lineHeight: "16px",
    whiteSpace: "nowrap",
  },
  body1: { fontSize: "14px", lineHeight: "20px" },
  body1Strong: { fontSize: "14px", lineHeight: "20px", fontWeight: 600 },
  caption1: { fontSize: "12px", lineHeight: "16px" },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    fontSize: "10px",
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "var(--aa-text)",
    backgroundColor: "rgba(91, 141, 239, 0.1)",
    border: "1px solid rgba(91, 141, 239, 0.22)",
    ...shorthands.borderRadius("999px"),
    ...shorthands.padding("4px", "10px"),
  },
  form: { display: "grid", gap: "18px" },
  fieldLabel: {
    color: "var(--aa-soft)",
    fontSize: "11px",
    fontWeight: 700,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    marginBottom: "6px",
  },
  fieldInput: { width: "100%" },
  inlineField: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: "10px",
    "@media (max-width: 640px)": {
      gridTemplateColumns: "1fr",
    },
  },
  actionRow: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "10px",
    flexWrap: "wrap",
  },
  scanResults: {
    display: "grid",
    gap: "12px",
    border: "1px solid var(--aa-hairline)",
    background: "linear-gradient(180deg, rgba(91, 141, 239, 0.06), rgba(255, 255, 255, 0.03))",
    boxShadow: "0 18px 40px rgba(0, 0, 0, 0.16)",
    ...shorthands.borderRadius("22px"),
    ...shorthands.padding("18px"),
  },
  scanRow: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    flexWrap: "wrap",
    fontSize: "13px",
    color: "var(--aa-text)",
  },
  scanLabel: {
    color: "var(--aa-soft)",
    minWidth: "88px",
    fontSize: "11px",
    fontWeight: 700,
    letterSpacing: "0.1em",
    textTransform: "uppercase",
  },
  errorText: { color: "var(--aa-copper)", fontSize: "13px", lineHeight: 1.6 },
  browserWrap: {
    border: "1px solid var(--aa-hairline)",
    background: "linear-gradient(180deg, rgba(255, 255, 255, 0.03), rgba(255, 255, 255, 0.02))",
    ...shorthands.borderRadius("22px"),
    ...shorthands.padding("14px"),
  },
  browserHeader: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "10px",
    fontSize: "12px",
    color: "var(--aa-muted)",
    overflowWrap: "anywhere",
  },
  browserList: { display: "grid", gap: "6px", maxHeight: "280px", overflowY: "auto" },
  browserEntry: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    width: "100%",
    background: "transparent",
    border: "1px solid transparent",
    color: "var(--aa-text-strong)",
    cursor: "pointer",
    textAlign: "left",
    fontSize: "13px",
    transitionDuration: "140ms",
    transitionProperty: "background-color, border-color",
    ...shorthands.borderRadius("14px"),
    ...shorthands.padding("10px", "12px"),
    ":hover": {
      backgroundColor: "rgba(255, 255, 255, 0.04)",
      border: "1px solid rgba(255, 255, 255, 0.08)",
    },
  },
  browserActions: { display: "flex", justifyContent: "flex-end", gap: "8px", marginTop: "12px" },
  dialogSurface: {
    backgroundColor: "var(--aa-bg)",
    border: "1px solid var(--aa-border)",
    color: "var(--aa-text-strong)",
    maxWidth: "520px",
  },
  dialogTitle: { color: "var(--aa-text-strong)", fontFamily: "var(--heading)" },
  dialogSpecNote: {
    display: "flex",
    gap: "10px",
    fontSize: "13px",
    lineHeight: "1.7",
    color: "var(--aa-text)",
    backgroundColor: "rgba(91, 141, 239, 0.06)",
    border: "1px solid rgba(91, 141, 239, 0.18)",
    ...shorthands.borderRadius("14px"),
    ...shorthands.padding("14px"),
  },
  dialogSpecIcon: { fontSize: "16px", flexShrink: 0, lineHeight: "1.6" },
  dialogError: { color: "var(--aa-copper)", fontSize: "13px", marginTop: "8px" },
});
