import { makeStyles, shorthands } from "@fluentui/react-components";

export const useCommandsPanelStyles = makeStyles({
  root: {
    minHeight: 0,
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "14px",
    overflowY: "auto",
    ...shorthands.padding("14px", "20px"),
    "@media (max-width: 1100px)": {
      gridTemplateColumns: "1fr",
    },
  },
  stack: {
    minHeight: 0,
    display: "grid",
    gap: "16px",
    alignContent: "start",
    overflowY: "auto",
  },
  section: {
    display: "grid",
    gap: "18px",
    border: "1px solid var(--aa-border)",
    background:
      "var(--aa-panel)",
    boxShadow: "none",
    ...shorthands.borderRadius("8px"),
    ...shorthands.padding("16px"),
  },
  hero: {
    position: "relative",
    overflow: "hidden",
    background:
      "var(--aa-panel)",
  },
  eyebrow: {
    display: "inline-flex",
    alignItems: "center",
    width: "fit-content",
    color: "var(--aa-soft)",
    backgroundColor: "rgba(91, 141, 239, 0.08)",
    border: "1px solid var(--aa-border)",
    ...shorthands.borderRadius("999px"),
    ...shorthands.padding("7px", "12px"),
    fontSize: "11px",
    fontWeight: 700,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
  },
  heroTitle: {
    margin: 0,
    fontFamily: "var(--mono)",
    fontSize: "14px",
    lineHeight: 1.1,
    color: "var(--aa-text-strong)",
  },
  heroDescription: {
    maxWidth: "64ch",
    color: "var(--aa-muted)",
    fontSize: "13px",
    lineHeight: 1.8,
  },
  metricRow: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: "14px",
    "@media (max-width: 720px)": {
      gridTemplateColumns: "1fr",
    },
  },
  metricCard: {
    display: "grid",
    gap: "8px",
    border: "1px solid var(--aa-border)",
    background: "var(--aa-bg)",
    ...shorthands.borderRadius("8px"),
    ...shorthands.padding("16px"),
  },
  metricLabel: {
    color: "var(--aa-soft)",
    fontSize: "11px",
    fontWeight: 700,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
  },
  metricValue: {
    color: "var(--aa-text-strong)",
    fontFamily: "var(--mono)",
    fontSize: "14px",
    fontWeight: 600,
  },
  metricNote: {
    color: "var(--aa-muted)",
    fontSize: "12px",
    lineHeight: 1.65,
  },
  commandGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: "14px",
  },
  commandCard: {
    display: "grid",
    gap: "12px",
    textAlign: "left",
    color: "inherit",
    border: "1px solid var(--aa-border)",
    background:
      "var(--aa-panel)",
    cursor: "pointer",
    transitionDuration: "180ms",
    transitionProperty: "transform, border-color, background-color, box-shadow",
    transitionTimingFunction: "ease",
    ...shorthands.borderRadius("8px"),
    ...shorthands.padding("16px"),
    ":hover": {
      transform: "translateY(-1px)",
      border: "1px solid var(--aa-border)",
      background: "var(--aa-panel)",
      boxShadow: "0 14px 36px rgba(0, 0, 0, 0.22)",
    },
  },
  commandCardActive: {
    border: "1px solid var(--aa-border)",
    background:
      "rgba(91, 141, 239, 0.12)",
    boxShadow: "0 18px 40px rgba(5, 10, 18, 0.32)",
  },
  commandMetaRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "10px",
    flexWrap: "wrap",
  },
  commandTitle: {
    color: "var(--aa-text-strong)",
    fontSize: "13px",
    fontWeight: 700,
  },
  commandDescription: {
    color: "var(--aa-muted)",
    fontSize: "13px",
    lineHeight: 1.65,
  },
  commandDetail: {
    color: "var(--aa-soft)",
    fontSize: "12px",
    lineHeight: 1.65,
  },
  composerHeader: {
    display: "grid",
    gap: "8px",
  },
  sectionTitle: {
    margin: 0,
    color: "var(--aa-text-strong)",
    fontSize: "13px",
    fontWeight: 700,
  },
  sectionText: {
    color: "var(--aa-muted)",
    fontSize: "13px",
    lineHeight: 1.7,
  },
  formGrid: {
    display: "grid",
    gap: "12px",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
  },
  field: {
    display: "grid",
    gap: "8px",
  },
  fieldWide: {
    gridColumn: "1 / -1",
  },
  fieldLabel: {
    color: "var(--aa-text-strong)",
    fontSize: "12px",
    fontWeight: 600,
  },
  fieldDescription: {
    color: "var(--aa-soft)",
    fontSize: "12px",
    lineHeight: 1.55,
  },
  input: {
    "& input, & textarea": {
      color: "var(--aa-text-strong)",
      backgroundColor: "rgba(7, 12, 20, 0.72)",
    },
  },
  actionRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: "12px",
    alignItems: "center",
    flexWrap: "wrap",
  },
  helperText: {
    color: "var(--aa-soft)",
    fontSize: "12px",
    lineHeight: 1.6,
  },
  helperWarning: {
    color: "var(--aa-soft)",
  },
  errorBox: {
    color: "var(--aa-copper)",
    border: "1px solid rgba(232, 93, 93, 0.22)",
    backgroundColor: "rgba(232, 93, 93, 0.08)",
    ...shorthands.borderRadius("6px"),
    ...shorthands.padding("12px", "14px"),
    fontSize: "13px",
    lineHeight: 1.65,
  },
  destructiveWarning: {
    display: "flex",
    alignItems: "flex-start",
    gap: "10px",
    color: "var(--aa-copper)",
    border: "1px solid rgba(232, 160, 60, 0.22)",
    backgroundColor: "rgba(232, 160, 60, 0.08)",
    ...shorthands.borderRadius("6px"),
    ...shorthands.padding("12px", "14px"),
    fontSize: "13px",
    lineHeight: 1.65,
  },
  resultRail: {
    minHeight: 0,
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr)",
    gap: "20px",
  },
  historyList: {
    minHeight: 0,
    overflowY: "auto",
    display: "grid",
    alignContent: "start",
    gap: "12px",
  },
  historyItem: {
    display: "grid",
    gap: "12px",
    border: "1px solid var(--aa-border)",
    background:
      "var(--aa-panel)",
    ...shorthands.borderRadius("8px"),
    ...shorthands.padding("16px"),
  },
  historyHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: "12px",
    flexWrap: "wrap",
    alignItems: "start",
  },
  historyTitleBlock: {
    display: "grid",
    gap: "6px",
  },
  historyTitle: {
    color: "var(--aa-text-strong)",
    fontSize: "13px",
    fontWeight: 700,
  },
  historyMeta: {
    color: "var(--aa-soft)",
    fontSize: "12px",
  },
  badgeRow: {
    display: "flex",
    gap: "8px",
    alignItems: "center",
    flexWrap: "wrap",
  },
  summaryGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(100px, 1fr))",
    gap: "10px",
  },
  summaryCard: {
    display: "grid",
    gap: "4px",
    border: "1px solid var(--aa-border)",
    backgroundColor: "var(--aa-bg)",
    ...shorthands.borderRadius("6px"),
    ...shorthands.padding("10px", "12px"),
  },
  summaryLabel: {
    color: "var(--aa-soft)",
    fontSize: "11px",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  summaryValue: {
    color: "var(--aa-text-strong)",
    fontSize: "13px",
    lineHeight: 1.5,
    wordBreak: "break-word",
  },
  recordList: {
    display: "grid",
    gap: "8px",
  },
  recordListItem: {
    display: "grid",
    gap: "4px",
    borderBottom: "1px solid var(--aa-border)",
    ...shorthands.padding("0", "0", "8px"),
  },
  recordPrimary: {
    color: "var(--aa-text)",
    fontSize: "13px",
  },
  recordSecondary: {
    color: "var(--aa-soft)",
    fontSize: "12px",
  },
  preview: {
    margin: 0,
    color: "var(--aa-text)",
    backgroundColor: "rgba(9, 12, 18, 0.86)",
    border: "1px solid rgba(91, 141, 239, 0.08)",
    fontFamily: "var(--mono)",
    fontSize: "12px",
    lineHeight: 1.7,
    overflowX: "auto",
    maxHeight: "320px",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    ...shorthands.borderRadius("6px"),
    ...shorthands.padding("14px"),
  },
  emptyState: {
    display: "grid",
    placeItems: "center",
    minHeight: "240px",
    color: "var(--aa-soft)",
    textAlign: "center",
    lineHeight: 1.8,
    border: "1px dashed var(--aa-border)",
    ...shorthands.borderRadius("8px"),
    ...shorthands.padding("24px"),
  },
});
