// <auto-generated />
using System;
using AgentAcademy.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgentAcademy.Server.Data.Migrations
{
    [DbContext(typeof(AgentAcademyDbContext))]
    [Migration("20260328173608_AddNotificationConfig")]
    partial class AddNotificationConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("AgentAcademy.Server.Data.Entities.ActivityEventEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Info");

                    b.Property<string>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("idx_activity_time");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("idx_activity_room");

                    b.ToTable("activity_events", (string)null);
                });

            modelBuilder.Entity("AgentAcademy.Server.Data.Entities.AgentLocationEntity", b =>
                {
                    b.Property<string>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BreakoutRoomId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Idle");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AgentId");

                    b.HasIndex("RoomId");

                    b.ToTable("agent_locations", (string)null);
                });

            modelBuilder.Entity("AgentAcademy.Server.Data.Entities.AgentMemoryEntity", b =>
                {
                    b.Property<string>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AgentId", "Key");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("idx_agent_memories_agent");

                    b.HasIndex("Category")
                        .HasDatabaseName("idx_agent_memories_category");

                    b.ToTable("agent_memories", (string)null);
                });

            modelBuilder.Entity("AgentAcademy.Server.Data.Entities.BreakoutMessageEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BreakoutRoomId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderRole")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BreakoutRoomId");

                    b.ToTable("breakout_messages", (string)null);
                });

            modelBuilder.Entity("AgentAcademy.Server.Data.Entities.BreakoutRoomEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedAgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentRoomId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentRoomId")
                        .HasDatabaseName("idx_breakout_rooms_parent");

                    b.ToTable("breakout_rooms", (string)null);
                });

            modelBuilder.Entity("AgentAcademy.Server.Data.Entities.CommandAuditEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArgsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Success");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("idx_cmd_audits_agent");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("idx_cmd_audits_correlation");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("idx_cmd_audits_time");

                    b.ToTable("command_audits", (string)null);
                });

            modelBuilder.Entity("AgentAcademy.Server.Data.Entities.MessageEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplyToMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderRole")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("idx_messages_room");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("idx_messages_sentAt");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("AgentAcademy.Server.Data.Entities.NotificationConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "Key")
                        .IsUnique()
                        .HasDatabaseName("idx_notification_configs_provider_key");

                    b.ToTable("notification_configs", (string)null);
                });

            modelBuilder.Entity("AgentAcademy.Server.Data.Entities.PlanEntity", b =>
                {
                    b.Property<string>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("RoomId");

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("AgentAcademy.Server.Data.Entities.RoomEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentPhase")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Intake");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Idle");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("AgentAcademy.Server.Data.Entities.TaskEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedAgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedAgentName")
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchName")
                        .HasColumnType("TEXT");

                    b.Property<int>("CommitCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentPhase")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Planning");

                    b.Property<string>("CurrentPlan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("FleetModels")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("ImplementationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("NotStarted");

                    b.Property<string>("ImplementationSummary")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("PreferredRoles")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<int?>("PullRequestNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PullRequestStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("PullRequestUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReviewRounds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("ReviewerAgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Active");

                    b.Property<string>("SuccessCriteria")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("TestsCreated")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UsedFleet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("NotStarted");

                    b.Property<string>("ValidationSummary")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAgentId")
                        .HasDatabaseName("idx_tasks_agent");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("idx_tasks_room");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_tasks_status");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("AgentAcademy.Server.Data.Entities.TaskItemEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BreakoutRoomId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Evidence")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feedback")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo")
                        .HasDatabaseName("idx_task_items_agent");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("idx_task_items_room");

                    b.ToTable("task_items", (string)null);
                });

            modelBuilder.Entity("AgentAcademy.Server.Data.Entities.WorkspaceEntity", b =>
                {
                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .HasColumnType("TEXT");

                    b.HasKey("Path");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("AgentAcademy.Server.Data.Entities.ActivityEventEntity", b =>
                {
                    b.HasOne("AgentAcademy.Server.Data.Entities.RoomEntity", "Room")
                        .WithMany("ActivityEvents")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Room");
                });

            modelBuilder.Entity("AgentAcademy.Server.Data.Entities.BreakoutMessageEntity", b =>
                {
                    b.HasOne("AgentAcademy.Server.Data.Entities.BreakoutRoomEntity", "BreakoutRoom")
                        .WithMany("Messages")
                        .HasForeignKey("BreakoutRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BreakoutRoom");
                });

            modelBuilder.Entity("AgentAcademy.Server.Data.Entities.BreakoutRoomEntity", b =>
                {
                    b.HasOne("AgentAcademy.Server.Data.Entities.RoomEntity", "ParentRoom")
                        .WithMany("BreakoutRooms")
                        .HasForeignKey("ParentRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentRoom");
                });

            modelBuilder.Entity("AgentAcademy.Server.Data.Entities.MessageEntity", b =>
                {
                    b.HasOne("AgentAcademy.Server.Data.Entities.RoomEntity", "Room")
                        .WithMany("Messages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("AgentAcademy.Server.Data.Entities.PlanEntity", b =>
                {
                    b.HasOne("AgentAcademy.Server.Data.Entities.RoomEntity", "Room")
                        .WithOne("Plan")
                        .HasForeignKey("AgentAcademy.Server.Data.Entities.PlanEntity", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("AgentAcademy.Server.Data.Entities.TaskEntity", b =>
                {
                    b.HasOne("AgentAcademy.Server.Data.Entities.RoomEntity", "Room")
                        .WithMany("Tasks")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Room");
                });

            modelBuilder.Entity("AgentAcademy.Server.Data.Entities.BreakoutRoomEntity", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("AgentAcademy.Server.Data.Entities.RoomEntity", b =>
                {
                    b.Navigation("ActivityEvents");

                    b.Navigation("BreakoutRooms");

                    b.Navigation("Messages");

                    b.Navigation("Plan");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
